/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tube_hexarotor_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

/* tube_hexarotor_model_expl_vde_adj:(i0[12],i1[12],i2[6],i3[0])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, *w2=w+13, w3, w4, *w5=w+27, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+65;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = 0.19 */
  w1 = 1.9000000000000003e-01;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 12, w2);
  /* #3: @3 = @2[9] */
  for (rr=(&w3), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #4: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #5: @4 = 4.7619 */
  w4 = 4.7619047619047619e+00;
  /* #6: @5 = input[1][0] */
  casadi_copy(arg[1], 12, w5);
  /* #7: {@6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17} = vertsplit(@5) */
  w6 = w5[0];
  w7 = w5[1];
  w8 = w5[2];
  w9 = w5[3];
  w10 = w5[4];
  w11 = w5[5];
  w12 = w5[6];
  w13 = w5[7];
  w14 = w5[8];
  w15 = w5[9];
  w16 = w5[10];
  w17 = w5[11];
  /* #8: @16 = (@4*@16) */
  w16  = (w4*w16);
  /* #9: @3 = (@3*@16) */
  w3 *= w16;
  /* #10: @18 = -0.19 */
  w18 = -1.9000000000000003e-01;
  /* #11: @19 = @2[10] */
  for (rr=(&w19), ss=w2+10; ss!=w2+11; ss+=1) *rr++ = *ss;
  /* #12: @20 = (@18*@19) */
  w20  = (w18*w19);
  /* #13: @4 = (@4*@15) */
  w4 *= w15;
  /* #14: @20 = (@20*@4) */
  w20 *= w4;
  /* #15: @3 = (@3+@20) */
  w3 += w20;
  /* #16: @20 = @2[6] */
  for (rr=(&w20), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #17: @15 = cos(@20) */
  w15 = cos( w20 );
  /* #18: @21 = @2[7] */
  for (rr=(&w21), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #19: @22 = cos(@21) */
  w22 = cos( w21 );
  /* #20: @23 = (@14/@22) */
  w23  = (w14/w22);
  /* #21: @24 = (@15*@23) */
  w24  = (w15*w23);
  /* #22: @3 = (@3+@24) */
  w3 += w24;
  /* #23: @20 = sin(@20) */
  w20 = sin( w20 );
  /* #24: @24 = (@20*@13) */
  w24  = (w20*w13);
  /* #25: @3 = (@3-@24) */
  w3 -= w24;
  /* #26: @24 = tan(@21) */
  w24 = tan( w21 );
  /* #27: @24 = (@24*@12) */
  w24 *= w12;
  /* #28: @25 = (@15*@24) */
  w25  = (w15*w24);
  /* #29: @3 = (@3+@25) */
  w3 += w25;
  /* #30: (@0[11] += @3) */
  for (rr=w0+11, ss=(&w3); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #31: @3 = @2[11] */
  for (rr=(&w3), ss=w2+11; ss!=w2+12; ss+=1) *rr++ = *ss;
  /* #32: @25 = (@3*@4) */
  w25  = (w3*w4);
  /* #33: @18 = (@18*@25) */
  w18 *= w25;
  /* #34: @25 = (@20*@23) */
  w25  = (w20*w23);
  /* #35: @18 = (@18+@25) */
  w18 += w25;
  /* #36: @25 = (@15*@13) */
  w25  = (w15*w13);
  /* #37: @18 = (@18+@25) */
  w18 += w25;
  /* #38: @25 = (@20*@24) */
  w25  = (w20*w24);
  /* #39: @18 = (@18+@25) */
  w18 += w25;
  /* #40: (@0[10] += @18) */
  for (rr=w0+10, ss=(&w18); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #41: @18 = (@3*@16) */
  w18  = (w3*w16);
  /* #42: @1 = (@1*@18) */
  w1 *= w18;
  /* #43: @1 = (@1+@12) */
  w1 += w12;
  /* #44: (@0[9] += @1) */
  for (rr=w0+9, ss=(&w1); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #45: @1 = @2[8] */
  for (rr=(&w1), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #46: @18 = cos(@1) */
  w18 = cos( w1 );
  /* #47: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #48: @25 = (@15*@21) */
  w25  = (w15*w21);
  /* #49: @26 = 9.81 */
  w26 = 9.8100000000000005e+00;
  /* #50: @27 = (@26*@10) */
  w27  = (w26*w10);
  /* #51: @28 = (@25*@27) */
  w28  = (w25*w27);
  /* #52: @28 = (@18*@28) */
  w28  = (w18*w28);
  /* #53: @28 = (-@28) */
  w28 = (- w28 );
  /* #54: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #55: @29 = (@20*@27) */
  w29  = (w20*w27);
  /* #56: @29 = (@1*@29) */
  w29  = (w1*w29);
  /* #57: @28 = (@28-@29) */
  w28 -= w29;
  /* #58: @29 = (@26*@9) */
  w29  = (w26*w9);
  /* #59: @30 = (@20*@29) */
  w30  = (w20*w29);
  /* #60: @30 = (@18*@30) */
  w30  = (w18*w30);
  /* #61: @28 = (@28-@30) */
  w28 -= w30;
  /* #62: @25 = (@25*@29) */
  w25 *= w29;
  /* #63: @25 = (@1*@25) */
  w25  = (w1*w25);
  /* #64: @28 = (@28+@25) */
  w28 += w25;
  /* #65: (@0[8] += @28) */
  for (rr=w0+8, ss=(&w28); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #66: @28 = (@3*@15) */
  w28  = (w3*w15);
  /* #67: @25 = (@28/@22) */
  w25  = (w28/w22);
  /* #68: @25 = (@25/@22) */
  w25 /= w22;
  /* #69: @25 = (@25*@14) */
  w25 *= w14;
  /* #70: @25 = (@21*@25) */
  w25  = (w21*w25);
  /* #71: @30 = (@19*@20) */
  w30  = (w19*w20);
  /* #72: @31 = (@30/@22) */
  w31  = (w30/w22);
  /* #73: @31 = (@31/@22) */
  w31 /= w22;
  /* #74: @31 = (@31*@14) */
  w31 *= w14;
  /* #75: @31 = (@21*@31) */
  w31  = (w21*w31);
  /* #76: @25 = (@25+@31) */
  w25 += w31;
  /* #77: @28 = (@28*@12) */
  w28 *= w12;
  /* #78: @31 = sq(@22) */
  w31 = casadi_sq( w22 );
  /* #79: @28 = (@28/@31) */
  w28 /= w31;
  /* #80: @25 = (@25+@28) */
  w25 += w28;
  /* #81: @30 = (@30*@12) */
  w30 *= w12;
  /* #82: @30 = (@30/@31) */
  w30 /= w31;
  /* #83: @25 = (@25+@30) */
  w25 += w30;
  /* #84: @26 = (@26*@11) */
  w26 *= w11;
  /* #85: @30 = (@15*@26) */
  w30  = (w15*w26);
  /* #86: @30 = (@21*@30) */
  w30  = (w21*w30);
  /* #87: @25 = (@25+@30) */
  w25 += w30;
  /* #88: @30 = (@1*@27) */
  w30  = (w1*w27);
  /* #89: @31 = (@15*@30) */
  w31  = (w15*w30);
  /* #90: @31 = (@22*@31) */
  w31  = (w22*w31);
  /* #91: @25 = (@25-@31) */
  w25 -= w31;
  /* #92: @31 = (@18*@29) */
  w31  = (w18*w29);
  /* #93: @12 = (@15*@31) */
  w12  = (w15*w31);
  /* #94: @12 = (@22*@12) */
  w12  = (w22*w12);
  /* #95: @25 = (@25-@12) */
  w25 -= w12;
  /* #96: (@0[7] += @25) */
  for (rr=w0+7, ss=(&w25); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #97: @25 = (@19*@23) */
  w25  = (w19*w23);
  /* #98: @25 = (@15*@25) */
  w25  = (w15*w25);
  /* #99: @23 = (@3*@23) */
  w23  = (w3*w23);
  /* #100: @23 = (@20*@23) */
  w23  = (w20*w23);
  /* #101: @25 = (@25-@23) */
  w25 -= w23;
  /* #102: @23 = (@3*@13) */
  w23  = (w3*w13);
  /* #103: @23 = (@15*@23) */
  w23  = (w15*w23);
  /* #104: @25 = (@25-@23) */
  w25 -= w23;
  /* #105: @13 = (@19*@13) */
  w13  = (w19*w13);
  /* #106: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #107: @25 = (@25-@13) */
  w25 -= w13;
  /* #108: @3 = (@3*@24) */
  w3 *= w24;
  /* #109: @3 = (@20*@3) */
  w3  = (w20*w3);
  /* #110: @25 = (@25-@3) */
  w25 -= w3;
  /* #111: @19 = (@19*@24) */
  w19 *= w24;
  /* #112: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #113: @25 = (@25+@19) */
  w25 += w19;
  /* #114: @22 = (@22*@26) */
  w22 *= w26;
  /* #115: @22 = (@20*@22) */
  w22  = (w20*w22);
  /* #116: @25 = (@25+@22) */
  w25 += w22;
  /* #117: @18 = (@18*@27) */
  w18 *= w27;
  /* #118: @18 = (@15*@18) */
  w18  = (w15*w18);
  /* #119: @25 = (@25+@18) */
  w25 += w18;
  /* #120: @30 = (@21*@30) */
  w30  = (w21*w30);
  /* #121: @30 = (@20*@30) */
  w30  = (w20*w30);
  /* #122: @25 = (@25+@30) */
  w25 += w30;
  /* #123: @1 = (@1*@29) */
  w1 *= w29;
  /* #124: @15 = (@15*@1) */
  w15 *= w1;
  /* #125: @25 = (@25-@15) */
  w25 -= w15;
  /* #126: @21 = (@21*@31) */
  w21 *= w31;
  /* #127: @20 = (@20*@21) */
  w20 *= w21;
  /* #128: @25 = (@25+@20) */
  w25 += w20;
  /* #129: (@0[6] += @25) */
  for (rr=w0+6, ss=(&w25); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #130: (@0[5] += @8) */
  for (rr=w0+5, ss=(&w8); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #131: (@0[4] += @7) */
  for (rr=w0+4, ss=(&w7); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #132: (@0[3] += @6) */
  for (rr=w0+3, ss=(&w6); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #133: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  /* #134: @32 = zeros(6x1) */
  casadi_clear(w32, 6);
  /* #135: @6 = 2.5 */
  w6 = 2.5000000000000000e+00;
  /* #136: @6 = (@6*@17) */
  w6 *= w17;
  /* #137: (@32[5] += @6) */
  for (rr=w32+5, ss=(&w6); rr!=w32+6; rr+=1) *rr += *ss++;
  /* #138: (@32[4] += @16) */
  for (rr=w32+4, ss=(&w16); rr!=w32+5; rr+=1) *rr += *ss++;
  /* #139: (@32[3] += @4) */
  for (rr=w32+3, ss=(&w4); rr!=w32+4; rr+=1) *rr += *ss++;
  /* #140: @4 = 0.162602 */
  w4 = 1.6260162601626016e-01;
  /* #141: @11 = (@4*@11) */
  w11  = (w4*w11);
  /* #142: (@32[2] += @11) */
  for (rr=w32+2, ss=(&w11); rr!=w32+3; rr+=1) *rr += *ss++;
  /* #143: @10 = (@4*@10) */
  w10  = (w4*w10);
  /* #144: (@32[1] += @10) */
  for (rr=w32+1, ss=(&w10); rr!=w32+2; rr+=1) *rr += *ss++;
  /* #145: @4 = (@4*@9) */
  w4 *= w9;
  /* #146: (@32[0] += @4) */
  for (rr=w32+0, ss=(&w4); rr!=w32+1; rr+=1) *rr += *ss++;
  /* #147: output[0][1] = @32 */
  if (res[0]) casadi_copy(w32, 6, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int tube_hexarotor_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tube_hexarotor_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tube_hexarotor_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tube_hexarotor_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tube_hexarotor_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tube_hexarotor_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tube_hexarotor_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void tube_hexarotor_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tube_hexarotor_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tube_hexarotor_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tube_hexarotor_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tube_hexarotor_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tube_hexarotor_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tube_hexarotor_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tube_hexarotor_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tube_hexarotor_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 71;
  return 0;
}

CASADI_SYMBOL_EXPORT int tube_hexarotor_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 71*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
