/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) full_hexarotor_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

/* full_hexarotor_model_expl_vde_adj:(i0[12],i1[12],i2[6],i3[0])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, *w2=w+13, w3, w4, *w5=w+27, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, *w26=w+59;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = 0.19 */
  w1 = 1.9000000000000003e-01;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 12, w2);
  /* #3: @3 = @2[9] */
  for (rr=(&w3), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #4: @3 = (@1*@3) */
  w3  = (w1*w3);
  /* #5: @4 = 4.7619 */
  w4 = 4.7619047619047619e+00;
  /* #6: @5 = input[1][0] */
  casadi_copy(arg[1], 12, w5);
  /* #7: {@6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17} = vertsplit(@5) */
  w6 = w5[0];
  w7 = w5[1];
  w8 = w5[2];
  w9 = w5[3];
  w10 = w5[4];
  w11 = w5[5];
  w12 = w5[6];
  w13 = w5[7];
  w14 = w5[8];
  w15 = w5[9];
  w16 = w5[10];
  w17 = w5[11];
  /* #8: @16 = (@4*@16) */
  w16  = (w4*w16);
  /* #9: @3 = (@3*@16) */
  w3 *= w16;
  /* #10: @18 = -0.19 */
  w18 = -1.9000000000000003e-01;
  /* #11: @19 = @2[10] */
  for (rr=(&w19), ss=w2+10; ss!=w2+11; ss+=1) *rr++ = *ss;
  /* #12: @20 = (@18*@19) */
  w20  = (w18*w19);
  /* #13: @4 = (@4*@15) */
  w4 *= w15;
  /* #14: @20 = (@20*@4) */
  w20 *= w4;
  /* #15: @3 = (@3+@20) */
  w3 += w20;
  /* #16: @20 = @2[6] */
  for (rr=(&w20), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #17: @15 = cos(@20) */
  w15 = cos( w20 );
  /* #18: @21 = @2[7] */
  for (rr=(&w21), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #19: @22 = cos(@21) */
  w22 = cos( w21 );
  /* #20: @23 = (@14/@22) */
  w23  = (w14/w22);
  /* #21: @24 = (@15*@23) */
  w24  = (w15*w23);
  /* #22: @3 = (@3+@24) */
  w3 += w24;
  /* #23: @20 = sin(@20) */
  w20 = sin( w20 );
  /* #24: @24 = (@20*@13) */
  w24  = (w20*w13);
  /* #25: @3 = (@3-@24) */
  w3 -= w24;
  /* #26: @24 = tan(@21) */
  w24 = tan( w21 );
  /* #27: @24 = (@24*@12) */
  w24 *= w12;
  /* #28: @25 = (@15*@24) */
  w25  = (w15*w24);
  /* #29: @3 = (@3+@25) */
  w3 += w25;
  /* #30: (@0[11] += @3) */
  for (rr=w0+11, ss=(&w3); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #31: @3 = @2[11] */
  for (rr=(&w3), ss=w2+11; ss!=w2+12; ss+=1) *rr++ = *ss;
  /* #32: @25 = (@3*@4) */
  w25  = (w3*w4);
  /* #33: @18 = (@18*@25) */
  w18 *= w25;
  /* #34: @25 = (@20*@23) */
  w25  = (w20*w23);
  /* #35: @18 = (@18+@25) */
  w18 += w25;
  /* #36: @25 = (@15*@13) */
  w25  = (w15*w13);
  /* #37: @18 = (@18+@25) */
  w18 += w25;
  /* #38: @25 = (@20*@24) */
  w25  = (w20*w24);
  /* #39: @18 = (@18+@25) */
  w18 += w25;
  /* #40: (@0[10] += @18) */
  for (rr=w0+10, ss=(&w18); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #41: @18 = (@3*@16) */
  w18  = (w3*w16);
  /* #42: @1 = (@1*@18) */
  w1 *= w18;
  /* #43: @1 = (@1+@12) */
  w1 += w12;
  /* #44: (@0[9] += @1) */
  for (rr=w0+9, ss=(&w1); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #45: @1 = (@19*@23) */
  w1  = (w19*w23);
  /* #46: @1 = (@15*@1) */
  w1  = (w15*w1);
  /* #47: @23 = (@3*@23) */
  w23  = (w3*w23);
  /* #48: @23 = (@20*@23) */
  w23  = (w20*w23);
  /* #49: @1 = (@1-@23) */
  w1 -= w23;
  /* #50: @23 = (@3*@13) */
  w23  = (w3*w13);
  /* #51: @23 = (@15*@23) */
  w23  = (w15*w23);
  /* #52: @1 = (@1-@23) */
  w1 -= w23;
  /* #53: @13 = (@19*@13) */
  w13  = (w19*w13);
  /* #54: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #55: @1 = (@1-@13) */
  w1 -= w13;
  /* #56: @13 = (@3*@24) */
  w13  = (w3*w24);
  /* #57: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #58: @1 = (@1-@13) */
  w1 -= w13;
  /* #59: @24 = (@19*@24) */
  w24  = (w19*w24);
  /* #60: @24 = (@15*@24) */
  w24  = (w15*w24);
  /* #61: @1 = (@1+@24) */
  w1 += w24;
  /* #62: @24 = 9.81 */
  w24 = 9.8100000000000005e+00;
  /* #63: @13 = (@22*@11) */
  w13  = (w22*w11);
  /* #64: @13 = (@24*@13) */
  w13  = (w24*w13);
  /* #65: @13 = (@20*@13) */
  w13  = (w20*w13);
  /* #66: @1 = (@1+@13) */
  w1 += w13;
  /* #67: @13 = (@22*@10) */
  w13  = (w22*w10);
  /* #68: @13 = (@24*@13) */
  w13  = (w24*w13);
  /* #69: @13 = (@15*@13) */
  w13  = (w15*w13);
  /* #70: @1 = (@1+@13) */
  w1 += w13;
  /* #71: (@0[6] += @1) */
  for (rr=w0+6, ss=(&w1); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #72: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #73: @3 = (@3*@15) */
  w3 *= w15;
  /* #74: @1 = (@3/@22) */
  w1  = (w3/w22);
  /* #75: @1 = (@1/@22) */
  w1 /= w22;
  /* #76: @1 = (@1*@14) */
  w1 *= w14;
  /* #77: @1 = (@21*@1) */
  w1  = (w21*w1);
  /* #78: @19 = (@19*@20) */
  w19 *= w20;
  /* #79: @13 = (@19/@22) */
  w13  = (w19/w22);
  /* #80: @13 = (@13/@22) */
  w13 /= w22;
  /* #81: @13 = (@13*@14) */
  w13 *= w14;
  /* #82: @13 = (@21*@13) */
  w13  = (w21*w13);
  /* #83: @1 = (@1+@13) */
  w1 += w13;
  /* #84: @3 = (@3*@12) */
  w3 *= w12;
  /* #85: @13 = sq(@22) */
  w13 = casadi_sq( w22 );
  /* #86: @3 = (@3/@13) */
  w3 /= w13;
  /* #87: @1 = (@1+@3) */
  w1 += w3;
  /* #88: @19 = (@19*@12) */
  w19 *= w12;
  /* #89: @19 = (@19/@13) */
  w19 /= w13;
  /* #90: @1 = (@1+@19) */
  w1 += w19;
  /* #91: @15 = (@24*@15) */
  w15  = (w24*w15);
  /* #92: @15 = (@15*@11) */
  w15 *= w11;
  /* #93: @15 = (@21*@15) */
  w15  = (w21*w15);
  /* #94: @1 = (@1+@15) */
  w1 += w15;
  /* #95: @20 = (@24*@20) */
  w20  = (w24*w20);
  /* #96: @20 = (@20*@10) */
  w20 *= w10;
  /* #97: @21 = (@21*@20) */
  w21 *= w20;
  /* #98: @1 = (@1-@21) */
  w1 -= w21;
  /* #99: @24 = (@24*@9) */
  w24 *= w9;
  /* #100: @22 = (@22*@24) */
  w22 *= w24;
  /* #101: @1 = (@1-@22) */
  w1 -= w22;
  /* #102: (@0[7] += @1) */
  for (rr=w0+7, ss=(&w1); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #103: (@0[5] += @8) */
  for (rr=w0+5, ss=(&w8); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #104: (@0[4] += @7) */
  for (rr=w0+4, ss=(&w7); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #105: (@0[3] += @6) */
  for (rr=w0+3, ss=(&w6); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #106: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  /* #107: @26 = zeros(6x1) */
  casadi_clear(w26, 6);
  /* #108: @6 = 2.5 */
  w6 = 2.5000000000000000e+00;
  /* #109: @6 = (@6*@17) */
  w6 *= w17;
  /* #110: (@26[5] += @6) */
  for (rr=w26+5, ss=(&w6); rr!=w26+6; rr+=1) *rr += *ss++;
  /* #111: (@26[4] += @16) */
  for (rr=w26+4, ss=(&w16); rr!=w26+5; rr+=1) *rr += *ss++;
  /* #112: (@26[3] += @4) */
  for (rr=w26+3, ss=(&w4); rr!=w26+4; rr+=1) *rr += *ss++;
  /* #113: @4 = 0.162602 */
  w4 = 1.6260162601626016e-01;
  /* #114: @11 = (@4*@11) */
  w11  = (w4*w11);
  /* #115: (@26[2] += @11) */
  for (rr=w26+2, ss=(&w11); rr!=w26+3; rr+=1) *rr += *ss++;
  /* #116: @10 = (@4*@10) */
  w10  = (w4*w10);
  /* #117: (@26[1] += @10) */
  for (rr=w26+1, ss=(&w10); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #118: @4 = (@4*@9) */
  w4 *= w9;
  /* #119: (@26[0] += @4) */
  for (rr=w26+0, ss=(&w4); rr!=w26+1; rr+=1) *rr += *ss++;
  /* #120: output[0][1] = @26 */
  if (res[0]) casadi_copy(w26, 6, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_hexarotor_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_hexarotor_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void full_hexarotor_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void full_hexarotor_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int full_hexarotor_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int full_hexarotor_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real full_hexarotor_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_hexarotor_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_hexarotor_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_hexarotor_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_hexarotor_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 65;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 65*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
