/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hexarotor_model_nominal_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

/* hexarotor_model_nominal_expl_vde_adj:(i0[12],i1[12],i2[6],i3[0])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, *w2=w+13, w3, w4, w5, *w6=w+28, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+65;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = 0.115262 */
  w1 = 1.1526178100000001e-01;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 12, w2);
  /* #3: @3 = @2[9] */
  for (rr=(&w3), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #4: @4 = (@1*@3) */
  w4  = (w1*w3);
  /* #5: @5 = 8.58191 */
  w5 = 8.5819061716340563e+00;
  /* #6: @6 = input[1][0] */
  casadi_copy(arg[1], 12, w6);
  /* #7: {@7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18} = vertsplit(@6) */
  w7 = w6[0];
  w8 = w6[1];
  w9 = w6[2];
  w10 = w6[3];
  w11 = w6[4];
  w12 = w6[5];
  w13 = w6[6];
  w14 = w6[7];
  w15 = w6[8];
  w16 = w6[9];
  w17 = w6[10];
  w18 = w6[11];
  /* #8: @5 = (@5*@17) */
  w5 *= w17;
  /* #9: @4 = (@4*@5) */
  w4 *= w5;
  /* #10: @17 = -0.113864 */
  w17 = -1.1386352300000001e-01;
  /* #11: @19 = @2[10] */
  for (rr=(&w19), ss=w2+10; ss!=w2+11; ss+=1) *rr++ = *ss;
  /* #12: @20 = (@17*@19) */
  w20  = (w17*w19);
  /* #13: @21 = 8.68614 */
  w21 = 8.6861373790280574e+00;
  /* #14: @21 = (@21*@16) */
  w21 *= w16;
  /* #15: @20 = (@20*@21) */
  w20 *= w21;
  /* #16: @4 = (@4+@20) */
  w4 += w20;
  /* #17: @20 = @2[6] */
  for (rr=(&w20), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #18: @16 = cos(@20) */
  w16 = cos( w20 );
  /* #19: @22 = @2[7] */
  for (rr=(&w22), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #20: @23 = cos(@22) */
  w23 = cos( w22 );
  /* #21: @24 = (@15/@23) */
  w24  = (w15/w23);
  /* #22: @25 = (@16*@24) */
  w25  = (w16*w24);
  /* #23: @4 = (@4+@25) */
  w4 += w25;
  /* #24: @20 = sin(@20) */
  w20 = sin( w20 );
  /* #25: @25 = (@20*@14) */
  w25  = (w20*w14);
  /* #26: @4 = (@4-@25) */
  w4 -= w25;
  /* #27: @25 = tan(@22) */
  w25 = tan( w22 );
  /* #28: @25 = (@25*@13) */
  w25 *= w13;
  /* #29: @26 = (@16*@25) */
  w26  = (w16*w25);
  /* #30: @4 = (@4+@26) */
  w4 += w26;
  /* #31: (@0[11] += @4) */
  for (rr=w0+11, ss=(&w4); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #32: @4 = -0.00139826 */
  w4 = -1.3982579999999994e-03;
  /* #33: @3 = (@4*@3) */
  w3  = (w4*w3);
  /* #34: @26 = 4.34051 */
  w26 = 4.3405085180048983e+00;
  /* #35: @26 = (@26*@18) */
  w26 *= w18;
  /* #36: @3 = (@3*@26) */
  w3 *= w26;
  /* #37: @18 = @2[11] */
  for (rr=(&w18), ss=w2+11; ss!=w2+12; ss+=1) *rr++ = *ss;
  /* #38: @27 = (@18*@21) */
  w27  = (w18*w21);
  /* #39: @17 = (@17*@27) */
  w17 *= w27;
  /* #40: @3 = (@3+@17) */
  w3 += w17;
  /* #41: @17 = (@20*@24) */
  w17  = (w20*w24);
  /* #42: @3 = (@3+@17) */
  w3 += w17;
  /* #43: @17 = (@16*@14) */
  w17  = (w16*w14);
  /* #44: @3 = (@3+@17) */
  w3 += w17;
  /* #45: @17 = (@20*@25) */
  w17  = (w20*w25);
  /* #46: @3 = (@3+@17) */
  w3 += w17;
  /* #47: (@0[10] += @3) */
  for (rr=w0+10, ss=(&w3); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #48: @3 = (@19*@26) */
  w3  = (w19*w26);
  /* #49: @4 = (@4*@3) */
  w4 *= w3;
  /* #50: @3 = (@18*@5) */
  w3  = (w18*w5);
  /* #51: @1 = (@1*@3) */
  w1 *= w3;
  /* #52: @4 = (@4+@1) */
  w4 += w1;
  /* #53: @4 = (@4+@13) */
  w4 += w13;
  /* #54: (@0[9] += @4) */
  for (rr=w0+9, ss=(&w4); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #55: @4 = @2[8] */
  for (rr=(&w4), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #56: @1 = cos(@4) */
  w1 = cos( w4 );
  /* #57: @22 = sin(@22) */
  w22 = sin( w22 );
  /* #58: @3 = (@16*@22) */
  w3  = (w16*w22);
  /* #59: @17 = 9.81 */
  w17 = 9.8100000000000005e+00;
  /* #60: @27 = (@17*@11) */
  w27  = (w17*w11);
  /* #61: @28 = (@3*@27) */
  w28  = (w3*w27);
  /* #62: @28 = (@1*@28) */
  w28  = (w1*w28);
  /* #63: @28 = (-@28) */
  w28 = (- w28 );
  /* #64: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #65: @29 = (@20*@27) */
  w29  = (w20*w27);
  /* #66: @29 = (@4*@29) */
  w29  = (w4*w29);
  /* #67: @28 = (@28-@29) */
  w28 -= w29;
  /* #68: @29 = (@17*@10) */
  w29  = (w17*w10);
  /* #69: @30 = (@20*@29) */
  w30  = (w20*w29);
  /* #70: @30 = (@1*@30) */
  w30  = (w1*w30);
  /* #71: @28 = (@28-@30) */
  w28 -= w30;
  /* #72: @3 = (@3*@29) */
  w3 *= w29;
  /* #73: @3 = (@4*@3) */
  w3  = (w4*w3);
  /* #74: @28 = (@28+@3) */
  w28 += w3;
  /* #75: (@0[8] += @28) */
  for (rr=w0+8, ss=(&w28); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #76: @28 = (@18*@16) */
  w28  = (w18*w16);
  /* #77: @3 = (@28/@23) */
  w3  = (w28/w23);
  /* #78: @3 = (@3/@23) */
  w3 /= w23;
  /* #79: @3 = (@3*@15) */
  w3 *= w15;
  /* #80: @3 = (@22*@3) */
  w3  = (w22*w3);
  /* #81: @30 = (@19*@20) */
  w30  = (w19*w20);
  /* #82: @31 = (@30/@23) */
  w31  = (w30/w23);
  /* #83: @31 = (@31/@23) */
  w31 /= w23;
  /* #84: @31 = (@31*@15) */
  w31 *= w15;
  /* #85: @31 = (@22*@31) */
  w31  = (w22*w31);
  /* #86: @3 = (@3+@31) */
  w3 += w31;
  /* #87: @28 = (@28*@13) */
  w28 *= w13;
  /* #88: @31 = sq(@23) */
  w31 = casadi_sq( w23 );
  /* #89: @28 = (@28/@31) */
  w28 /= w31;
  /* #90: @3 = (@3+@28) */
  w3 += w28;
  /* #91: @30 = (@30*@13) */
  w30 *= w13;
  /* #92: @30 = (@30/@31) */
  w30 /= w31;
  /* #93: @3 = (@3+@30) */
  w3 += w30;
  /* #94: @17 = (@17*@12) */
  w17 *= w12;
  /* #95: @30 = (@16*@17) */
  w30  = (w16*w17);
  /* #96: @30 = (@22*@30) */
  w30  = (w22*w30);
  /* #97: @3 = (@3+@30) */
  w3 += w30;
  /* #98: @30 = (@4*@27) */
  w30  = (w4*w27);
  /* #99: @31 = (@16*@30) */
  w31  = (w16*w30);
  /* #100: @31 = (@23*@31) */
  w31  = (w23*w31);
  /* #101: @3 = (@3-@31) */
  w3 -= w31;
  /* #102: @31 = (@1*@29) */
  w31  = (w1*w29);
  /* #103: @13 = (@16*@31) */
  w13  = (w16*w31);
  /* #104: @13 = (@23*@13) */
  w13  = (w23*w13);
  /* #105: @3 = (@3-@13) */
  w3 -= w13;
  /* #106: (@0[7] += @3) */
  for (rr=w0+7, ss=(&w3); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #107: @3 = (@19*@24) */
  w3  = (w19*w24);
  /* #108: @3 = (@16*@3) */
  w3  = (w16*w3);
  /* #109: @24 = (@18*@24) */
  w24  = (w18*w24);
  /* #110: @24 = (@20*@24) */
  w24  = (w20*w24);
  /* #111: @3 = (@3-@24) */
  w3 -= w24;
  /* #112: @24 = (@18*@14) */
  w24  = (w18*w14);
  /* #113: @24 = (@16*@24) */
  w24  = (w16*w24);
  /* #114: @3 = (@3-@24) */
  w3 -= w24;
  /* #115: @14 = (@19*@14) */
  w14  = (w19*w14);
  /* #116: @14 = (@20*@14) */
  w14  = (w20*w14);
  /* #117: @3 = (@3-@14) */
  w3 -= w14;
  /* #118: @18 = (@18*@25) */
  w18 *= w25;
  /* #119: @18 = (@20*@18) */
  w18  = (w20*w18);
  /* #120: @3 = (@3-@18) */
  w3 -= w18;
  /* #121: @19 = (@19*@25) */
  w19 *= w25;
  /* #122: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #123: @3 = (@3+@19) */
  w3 += w19;
  /* #124: @23 = (@23*@17) */
  w23 *= w17;
  /* #125: @23 = (@20*@23) */
  w23  = (w20*w23);
  /* #126: @3 = (@3+@23) */
  w3 += w23;
  /* #127: @1 = (@1*@27) */
  w1 *= w27;
  /* #128: @1 = (@16*@1) */
  w1  = (w16*w1);
  /* #129: @3 = (@3+@1) */
  w3 += w1;
  /* #130: @30 = (@22*@30) */
  w30  = (w22*w30);
  /* #131: @30 = (@20*@30) */
  w30  = (w20*w30);
  /* #132: @3 = (@3+@30) */
  w3 += w30;
  /* #133: @4 = (@4*@29) */
  w4 *= w29;
  /* #134: @16 = (@16*@4) */
  w16 *= w4;
  /* #135: @3 = (@3-@16) */
  w3 -= w16;
  /* #136: @22 = (@22*@31) */
  w22 *= w31;
  /* #137: @20 = (@20*@22) */
  w20 *= w22;
  /* #138: @3 = (@3+@20) */
  w3 += w20;
  /* #139: (@0[6] += @3) */
  for (rr=w0+6, ss=(&w3); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #140: (@0[5] += @9) */
  for (rr=w0+5, ss=(&w9); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #141: (@0[4] += @8) */
  for (rr=w0+4, ss=(&w8); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #142: (@0[3] += @7) */
  for (rr=w0+3, ss=(&w7); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #143: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  /* #144: @32 = zeros(6x1) */
  casadi_clear(w32, 6);
  /* #145: (@32[5] += @26) */
  for (rr=w32+5, ss=(&w26); rr!=w32+6; rr+=1) *rr += *ss++;
  /* #146: (@32[4] += @5) */
  for (rr=w32+4, ss=(&w5); rr!=w32+5; rr+=1) *rr += *ss++;
  /* #147: (@32[3] += @21) */
  for (rr=w32+3, ss=(&w21); rr!=w32+4; rr+=1) *rr += *ss++;
  /* #148: @21 = 0.142857 */
  w21 = 1.4285714285714285e-01;
  /* #149: @12 = (@21*@12) */
  w12  = (w21*w12);
  /* #150: (@32[2] += @12) */
  for (rr=w32+2, ss=(&w12); rr!=w32+3; rr+=1) *rr += *ss++;
  /* #151: @11 = (@21*@11) */
  w11  = (w21*w11);
  /* #152: (@32[1] += @11) */
  for (rr=w32+1, ss=(&w11); rr!=w32+2; rr+=1) *rr += *ss++;
  /* #153: @21 = (@21*@10) */
  w21 *= w10;
  /* #154: (@32[0] += @21) */
  for (rr=w32+0, ss=(&w21); rr!=w32+1; rr+=1) *rr += *ss++;
  /* #155: output[0][1] = @32 */
  if (res[0]) casadi_copy(w32, 6, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_nominal_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hexarotor_model_nominal_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_nominal_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hexarotor_model_nominal_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hexarotor_model_nominal_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hexarotor_model_nominal_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hexarotor_model_nominal_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void hexarotor_model_nominal_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hexarotor_model_nominal_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int hexarotor_model_nominal_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hexarotor_model_nominal_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hexarotor_model_nominal_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hexarotor_model_nominal_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hexarotor_model_nominal_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hexarotor_model_nominal_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hexarotor_model_nominal_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 71;
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_nominal_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 71*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
