/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) full_hexarotor_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};

/* full_hexarotor_model_expl_ode_fun:(i0[12],i1[6],i2[0])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, *w2=w+13, w3, w4, w5, w6, w7, w8, w9, w10, w11;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 12, w0);
  /* #1: @1 = @0[3] */
  for (rr=(&w1), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[4] */
  for (rr=(&w1), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @1 = @0[5] */
  for (rr=(&w1), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #7: @2 = input[1][0] */
  casadi_copy(arg[1], 6, w2);
  /* #8: @1 = @2[0] */
  for (rr=(&w1), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #9: @3 = 7 */
  w3 = 7.;
  /* #10: @1 = (@1/@3) */
  w1 /= w3;
  /* #11: @4 = 9.81 */
  w4 = 9.8100000000000005e+00;
  /* #12: @5 = @0[7] */
  for (rr=(&w5), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #13: @6 = sin(@5) */
  w6 = sin( w5 );
  /* #14: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #15: @1 = (@1-@6) */
  w1 -= w6;
  /* #16: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #17: @1 = @2[1] */
  for (rr=(&w1), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #18: @1 = (@1/@3) */
  w1 /= w3;
  /* #19: @6 = @0[6] */
  for (rr=(&w6), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #20: @7 = sin(@6) */
  w7 = sin( w6 );
  /* #21: @8 = (@4*@7) */
  w8  = (w4*w7);
  /* #22: @9 = cos(@5) */
  w9 = cos( w5 );
  /* #23: @8 = (@8*@9) */
  w8 *= w9;
  /* #24: @1 = (@1+@8) */
  w1 += w8;
  /* #25: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #26: @1 = @2[2] */
  for (rr=(&w1), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #27: @1 = (@1/@3) */
  w1 /= w3;
  /* #28: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #29: @4 = (@4*@6) */
  w4 *= w6;
  /* #30: @4 = (@4*@9) */
  w4 *= w9;
  /* #31: @1 = (@1-@4) */
  w1 -= w4;
  /* #32: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #33: @1 = @0[9] */
  for (rr=(&w1), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #34: @4 = @0[10] */
  for (rr=(&w4), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #35: @3 = (@4*@7) */
  w3  = (w4*w7);
  /* #36: @5 = tan(@5) */
  w5 = tan( w5 );
  /* #37: @8 = (@3*@5) */
  w8  = (w3*w5);
  /* #38: @8 = (@1+@8) */
  w8  = (w1+w8);
  /* #39: @10 = @0[11] */
  for (rr=(&w10), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #40: @11 = (@10*@6) */
  w11  = (w10*w6);
  /* #41: @5 = (@11*@5) */
  w5  = (w11*w5);
  /* #42: @8 = (@8+@5) */
  w8 += w5;
  /* #43: output[0][6] = @8 */
  if (res[0]) res[0][6] = w8;
  /* #44: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #45: @7 = (@10*@7) */
  w7  = (w10*w7);
  /* #46: @6 = (@6-@7) */
  w6 -= w7;
  /* #47: output[0][7] = @6 */
  if (res[0]) res[0][7] = w6;
  /* #48: @3 = (@3/@9) */
  w3 /= w9;
  /* #49: @11 = (@11/@9) */
  w11 /= w9;
  /* #50: @3 = (@3+@11) */
  w3 += w11;
  /* #51: output[0][8] = @3 */
  if (res[0]) res[0][8] = w3;
  /* #52: @3 = 8.68614 */
  w3 = 8.6861373790280574e+00;
  /* #53: @11 = @2[3] */
  for (rr=(&w11), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #54: @9 = -0.113864 */
  w9 = -1.1386352300000001e-01;
  /* #55: @9 = (@9*@4) */
  w9 *= w4;
  /* #56: @9 = (@9*@10) */
  w9 *= w10;
  /* #57: @11 = (@11+@9) */
  w11 += w9;
  /* #58: @3 = (@3*@11) */
  w3 *= w11;
  /* #59: output[0][9] = @3 */
  if (res[0]) res[0][9] = w3;
  /* #60: @3 = 8.58191 */
  w3 = 8.5819061716340563e+00;
  /* #61: @11 = @2[4] */
  for (rr=(&w11), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #62: @9 = 0.115262 */
  w9 = 1.1526178100000001e-01;
  /* #63: @9 = (@9*@1) */
  w9 *= w1;
  /* #64: @9 = (@9*@10) */
  w9 *= w10;
  /* #65: @11 = (@11+@9) */
  w11 += w9;
  /* #66: @3 = (@3*@11) */
  w3 *= w11;
  /* #67: output[0][10] = @3 */
  if (res[0]) res[0][10] = w3;
  /* #68: @3 = 4.34051 */
  w3 = 4.3405085180048983e+00;
  /* #69: @11 = @2[5] */
  for (rr=(&w11), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #70: @9 = -0.00139826 */
  w9 = -1.3982579999999994e-03;
  /* #71: @9 = (@9*@1) */
  w9 *= w1;
  /* #72: @9 = (@9*@4) */
  w9 *= w4;
  /* #73: @11 = (@11+@9) */
  w11 += w9;
  /* #74: @3 = (@3*@11) */
  w3 *= w11;
  /* #75: output[0][11] = @3 */
  if (res[0]) res[0][11] = w3;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_hexarotor_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_hexarotor_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void full_hexarotor_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void full_hexarotor_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int full_hexarotor_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int full_hexarotor_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real full_hexarotor_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_hexarotor_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_hexarotor_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_hexarotor_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_hexarotor_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 28;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_hexarotor_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 28*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
