/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hexarotor_model_adaptive_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};

/* hexarotor_model_adaptive_expl_vde_adj:(i0[16],i1[16],i2[6],i3[0])->(o0[22]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, *w2=w+17, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+63;
  /* #0: @0 = zeros(16x1) */
  casadi_clear(w0, 16);
  /* #1: @1 = 4.34051 */
  w1 = 4.3405085180048983e+00;
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 16, w2);
  /* #3: {@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, NULL} = vertsplit(@2) */
  w3 = w2[0];
  w4 = w2[1];
  w5 = w2[2];
  w6 = w2[3];
  w7 = w2[4];
  w8 = w2[5];
  w9 = w2[6];
  w10 = w2[7];
  w11 = w2[8];
  w12 = w2[9];
  w13 = w2[10];
  w14 = w2[11];
  /* #4: @1 = (@1*@14) */
  w1 *= w14;
  /* #5: (@0[15] += @1) */
  for (rr=w0+15, ss=(&w1); rr!=w0+16; rr+=1) *rr += *ss++;
  /* #6: @14 = 8.58191 */
  w14 = 8.5819061716340563e+00;
  /* #7: @14 = (@14*@13) */
  w14 *= w13;
  /* #8: (@0[14] += @14) */
  for (rr=w0+14, ss=(&w14); rr!=w0+15; rr+=1) *rr += *ss++;
  /* #9: @13 = 8.68614 */
  w13 = 8.6861373790280574e+00;
  /* #10: @13 = (@13*@12) */
  w13 *= w12;
  /* #11: (@0[13] += @13) */
  for (rr=w0+13, ss=(&w13); rr!=w0+14; rr+=1) *rr += *ss++;
  /* #12: @12 = 0.115262 */
  w12 = 1.1526178100000001e-01;
  /* #13: @2 = input[0][0] */
  casadi_copy(arg[0], 16, w2);
  /* #14: @15 = @2[9] */
  for (rr=(&w15), ss=w2+9; ss!=w2+10; ss+=1) *rr++ = *ss;
  /* #15: @16 = (@12*@15) */
  w16  = (w12*w15);
  /* #16: @16 = (@16*@14) */
  w16 *= w14;
  /* #17: @17 = -0.113864 */
  w17 = -1.1386352300000001e-01;
  /* #18: @18 = @2[10] */
  for (rr=(&w18), ss=w2+10; ss!=w2+11; ss+=1) *rr++ = *ss;
  /* #19: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #20: @19 = (@19*@13) */
  w19 *= w13;
  /* #21: @16 = (@16+@19) */
  w16 += w19;
  /* #22: @19 = @2[6] */
  for (rr=(&w19), ss=w2+6; ss!=w2+7; ss+=1) *rr++ = *ss;
  /* #23: @20 = cos(@19) */
  w20 = cos( w19 );
  /* #24: @21 = @2[7] */
  for (rr=(&w21), ss=w2+7; ss!=w2+8; ss+=1) *rr++ = *ss;
  /* #25: @22 = cos(@21) */
  w22 = cos( w21 );
  /* #26: @23 = (@11/@22) */
  w23  = (w11/w22);
  /* #27: @24 = (@20*@23) */
  w24  = (w20*w23);
  /* #28: @16 = (@16+@24) */
  w16 += w24;
  /* #29: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #30: @24 = (@19*@10) */
  w24  = (w19*w10);
  /* #31: @16 = (@16-@24) */
  w16 -= w24;
  /* #32: @24 = tan(@21) */
  w24 = tan( w21 );
  /* #33: @24 = (@24*@9) */
  w24 *= w9;
  /* #34: @25 = (@20*@24) */
  w25  = (w20*w24);
  /* #35: @16 = (@16+@25) */
  w16 += w25;
  /* #36: (@0[11] += @16) */
  for (rr=w0+11, ss=(&w16); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #37: @16 = -0.00139826 */
  w16 = -1.3982579999999994e-03;
  /* #38: @15 = (@16*@15) */
  w15  = (w16*w15);
  /* #39: @15 = (@15*@1) */
  w15 *= w1;
  /* #40: @25 = @2[11] */
  for (rr=(&w25), ss=w2+11; ss!=w2+12; ss+=1) *rr++ = *ss;
  /* #41: @26 = (@25*@13) */
  w26  = (w25*w13);
  /* #42: @17 = (@17*@26) */
  w17 *= w26;
  /* #43: @15 = (@15+@17) */
  w15 += w17;
  /* #44: @17 = (@19*@23) */
  w17  = (w19*w23);
  /* #45: @15 = (@15+@17) */
  w15 += w17;
  /* #46: @17 = (@20*@10) */
  w17  = (w20*w10);
  /* #47: @15 = (@15+@17) */
  w15 += w17;
  /* #48: @17 = (@19*@24) */
  w17  = (w19*w24);
  /* #49: @15 = (@15+@17) */
  w15 += w17;
  /* #50: (@0[10] += @15) */
  for (rr=w0+10, ss=(&w15); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #51: @15 = (@18*@1) */
  w15  = (w18*w1);
  /* #52: @16 = (@16*@15) */
  w16 *= w15;
  /* #53: @15 = (@25*@14) */
  w15  = (w25*w14);
  /* #54: @12 = (@12*@15) */
  w12 *= w15;
  /* #55: @16 = (@16+@12) */
  w16 += w12;
  /* #56: @16 = (@16+@9) */
  w16 += w9;
  /* #57: (@0[9] += @16) */
  for (rr=w0+9, ss=(&w16); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #58: @16 = 0.142857 */
  w16 = 1.4285714285714285e-01;
  /* #59: @12 = (@16*@8) */
  w12  = (w16*w8);
  /* #60: (@0[12] += @12) */
  for (rr=w0+12, ss=(&w12); rr!=w0+13; rr+=1) *rr += *ss++;
  /* #61: @15 = @2[8] */
  for (rr=(&w15), ss=w2+8; ss!=w2+9; ss+=1) *rr++ = *ss;
  /* #62: @17 = cos(@15) */
  w17 = cos( w15 );
  /* #63: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #64: @26 = (@20*@21) */
  w26  = (w20*w21);
  /* #65: @27 = 9.81 */
  w27 = 9.8100000000000005e+00;
  /* #66: @28 = (@27*@7) */
  w28  = (w27*w7);
  /* #67: @29 = (@26*@28) */
  w29  = (w26*w28);
  /* #68: @29 = (@17*@29) */
  w29  = (w17*w29);
  /* #69: @29 = (-@29) */
  w29 = (- w29 );
  /* #70: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #71: @30 = (@19*@28) */
  w30  = (w19*w28);
  /* #72: @30 = (@15*@30) */
  w30  = (w15*w30);
  /* #73: @29 = (@29-@30) */
  w29 -= w30;
  /* #74: @30 = (@27*@6) */
  w30  = (w27*w6);
  /* #75: @31 = (@19*@30) */
  w31  = (w19*w30);
  /* #76: @31 = (@17*@31) */
  w31  = (w17*w31);
  /* #77: @29 = (@29-@31) */
  w29 -= w31;
  /* #78: @26 = (@26*@30) */
  w26 *= w30;
  /* #79: @26 = (@15*@26) */
  w26  = (w15*w26);
  /* #80: @29 = (@29+@26) */
  w29 += w26;
  /* #81: (@0[8] += @29) */
  for (rr=w0+8, ss=(&w29); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #82: @29 = (@25*@20) */
  w29  = (w25*w20);
  /* #83: @26 = (@29/@22) */
  w26  = (w29/w22);
  /* #84: @26 = (@26/@22) */
  w26 /= w22;
  /* #85: @26 = (@26*@11) */
  w26 *= w11;
  /* #86: @26 = (@21*@26) */
  w26  = (w21*w26);
  /* #87: @31 = (@18*@19) */
  w31  = (w18*w19);
  /* #88: @32 = (@31/@22) */
  w32  = (w31/w22);
  /* #89: @32 = (@32/@22) */
  w32 /= w22;
  /* #90: @32 = (@32*@11) */
  w32 *= w11;
  /* #91: @32 = (@21*@32) */
  w32  = (w21*w32);
  /* #92: @26 = (@26+@32) */
  w26 += w32;
  /* #93: @29 = (@29*@9) */
  w29 *= w9;
  /* #94: @32 = sq(@22) */
  w32 = casadi_sq( w22 );
  /* #95: @29 = (@29/@32) */
  w29 /= w32;
  /* #96: @26 = (@26+@29) */
  w26 += w29;
  /* #97: @31 = (@31*@9) */
  w31 *= w9;
  /* #98: @31 = (@31/@32) */
  w31 /= w32;
  /* #99: @26 = (@26+@31) */
  w26 += w31;
  /* #100: @27 = (@27*@8) */
  w27 *= w8;
  /* #101: @8 = (@20*@27) */
  w8  = (w20*w27);
  /* #102: @8 = (@21*@8) */
  w8  = (w21*w8);
  /* #103: @26 = (@26+@8) */
  w26 += w8;
  /* #104: @8 = (@15*@28) */
  w8  = (w15*w28);
  /* #105: @31 = (@20*@8) */
  w31  = (w20*w8);
  /* #106: @31 = (@22*@31) */
  w31  = (w22*w31);
  /* #107: @26 = (@26-@31) */
  w26 -= w31;
  /* #108: @31 = (@17*@30) */
  w31  = (w17*w30);
  /* #109: @32 = (@20*@31) */
  w32  = (w20*w31);
  /* #110: @32 = (@22*@32) */
  w32  = (w22*w32);
  /* #111: @26 = (@26-@32) */
  w26 -= w32;
  /* #112: (@0[7] += @26) */
  for (rr=w0+7, ss=(&w26); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #113: @26 = (@18*@23) */
  w26  = (w18*w23);
  /* #114: @26 = (@20*@26) */
  w26  = (w20*w26);
  /* #115: @23 = (@25*@23) */
  w23  = (w25*w23);
  /* #116: @23 = (@19*@23) */
  w23  = (w19*w23);
  /* #117: @26 = (@26-@23) */
  w26 -= w23;
  /* #118: @23 = (@25*@10) */
  w23  = (w25*w10);
  /* #119: @23 = (@20*@23) */
  w23  = (w20*w23);
  /* #120: @26 = (@26-@23) */
  w26 -= w23;
  /* #121: @10 = (@18*@10) */
  w10  = (w18*w10);
  /* #122: @10 = (@19*@10) */
  w10  = (w19*w10);
  /* #123: @26 = (@26-@10) */
  w26 -= w10;
  /* #124: @25 = (@25*@24) */
  w25 *= w24;
  /* #125: @25 = (@19*@25) */
  w25  = (w19*w25);
  /* #126: @26 = (@26-@25) */
  w26 -= w25;
  /* #127: @18 = (@18*@24) */
  w18 *= w24;
  /* #128: @18 = (@20*@18) */
  w18  = (w20*w18);
  /* #129: @26 = (@26+@18) */
  w26 += w18;
  /* #130: @22 = (@22*@27) */
  w22 *= w27;
  /* #131: @22 = (@19*@22) */
  w22  = (w19*w22);
  /* #132: @26 = (@26+@22) */
  w26 += w22;
  /* #133: @17 = (@17*@28) */
  w17 *= w28;
  /* #134: @17 = (@20*@17) */
  w17  = (w20*w17);
  /* #135: @26 = (@26+@17) */
  w26 += w17;
  /* #136: @8 = (@21*@8) */
  w8  = (w21*w8);
  /* #137: @8 = (@19*@8) */
  w8  = (w19*w8);
  /* #138: @26 = (@26+@8) */
  w26 += w8;
  /* #139: @15 = (@15*@30) */
  w15 *= w30;
  /* #140: @20 = (@20*@15) */
  w20 *= w15;
  /* #141: @26 = (@26-@20) */
  w26 -= w20;
  /* #142: @21 = (@21*@31) */
  w21 *= w31;
  /* #143: @19 = (@19*@21) */
  w19 *= w21;
  /* #144: @26 = (@26+@19) */
  w26 += w19;
  /* #145: (@0[6] += @26) */
  for (rr=w0+6, ss=(&w26); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #146: (@0[5] += @5) */
  for (rr=w0+5, ss=(&w5); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #147: (@0[4] += @4) */
  for (rr=w0+4, ss=(&w4); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #148: (@0[3] += @3) */
  for (rr=w0+3, ss=(&w3); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #149: output[0][0] = @0 */
  casadi_copy(w0, 16, res[0]);
  /* #150: @33 = zeros(6x1) */
  casadi_clear(w33, 6);
  /* #151: (@33[5] += @1) */
  for (rr=w33+5, ss=(&w1); rr!=w33+6; rr+=1) *rr += *ss++;
  /* #152: (@33[4] += @14) */
  for (rr=w33+4, ss=(&w14); rr!=w33+5; rr+=1) *rr += *ss++;
  /* #153: (@33[3] += @13) */
  for (rr=w33+3, ss=(&w13); rr!=w33+4; rr+=1) *rr += *ss++;
  /* #154: (@33[2] += @12) */
  for (rr=w33+2, ss=(&w12); rr!=w33+3; rr+=1) *rr += *ss++;
  /* #155: @7 = (@16*@7) */
  w7  = (w16*w7);
  /* #156: (@33[1] += @7) */
  for (rr=w33+1, ss=(&w7); rr!=w33+2; rr+=1) *rr += *ss++;
  /* #157: @16 = (@16*@6) */
  w16 *= w6;
  /* #158: (@33[0] += @16) */
  for (rr=w33+0, ss=(&w16); rr!=w33+1; rr+=1) *rr += *ss++;
  /* #159: output[0][1] = @33 */
  if (res[0]) casadi_copy(w33, 6, res[0]+16);
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hexarotor_model_adaptive_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hexarotor_model_adaptive_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hexarotor_model_adaptive_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void hexarotor_model_adaptive_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hexarotor_model_adaptive_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int hexarotor_model_adaptive_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hexarotor_model_adaptive_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hexarotor_model_adaptive_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hexarotor_model_adaptive_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hexarotor_model_adaptive_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hexarotor_model_adaptive_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 69;
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 14*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 69*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
