/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hexarotor_model_adaptive_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};

/* hexarotor_model_adaptive_expl_ode_fun:(i0[16],i1[6],i2[0])->(o0[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, *w2=w+17, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+33;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: @1 = @0[3] */
  for (rr=(&w1), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[4] */
  for (rr=(&w1), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @1 = @0[5] */
  for (rr=(&w1), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #7: @2 = input[1][0] */
  casadi_copy(arg[1], 6, w2);
  /* #8: @1 = @2[0] */
  for (rr=(&w1), ss=w2+0; ss!=w2+1; ss+=1) *rr++ = *ss;
  /* #9: @3 = 7 */
  w3 = 7.;
  /* #10: @1 = (@1/@3) */
  w1 /= w3;
  /* #11: @4 = 9.81 */
  w4 = 9.8100000000000005e+00;
  /* #12: @5 = @0[6] */
  for (rr=(&w5), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #13: @6 = cos(@5) */
  w6 = cos( w5 );
  /* #14: @7 = @0[7] */
  for (rr=(&w7), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #15: @8 = sin(@7) */
  w8 = sin( w7 );
  /* #16: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #17: @9 = @0[8] */
  for (rr=(&w9), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #18: @10 = cos(@9) */
  w10 = cos( w9 );
  /* #19: @11 = (@8*@10) */
  w11  = (w8*w10);
  /* #20: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #21: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #22: @12 = (@5*@9) */
  w12  = (w5*w9);
  /* #23: @11 = (@11+@12) */
  w11 += w12;
  /* #24: @11 = (@4*@11) */
  w11  = (w4*w11);
  /* #25: @1 = (@1-@11) */
  w1 -= w11;
  /* #26: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #27: @1 = @2[1] */
  for (rr=(&w1), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #28: @1 = (@1/@3) */
  w1 /= w3;
  /* #29: @8 = (@8*@9) */
  w8 *= w9;
  /* #30: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #31: @8 = (@8-@10) */
  w8 -= w10;
  /* #32: @8 = (@4*@8) */
  w8  = (w4*w8);
  /* #33: @1 = (@1-@8) */
  w1 -= w8;
  /* #34: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #35: @1 = @2[2] */
  for (rr=(&w1), ss=w2+2; ss!=w2+3; ss+=1) *rr++ = *ss;
  /* #36: @8 = @0[12] */
  for (rr=(&w8), ss=w0+12; ss!=w0+13; ss+=1) *rr++ = *ss;
  /* #37: @1 = (@1+@8) */
  w1 += w8;
  /* #38: @1 = (@1/@3) */
  w1 /= w3;
  /* #39: @3 = cos(@7) */
  w3 = cos( w7 );
  /* #40: @8 = (@6*@3) */
  w8  = (w6*w3);
  /* #41: @4 = (@4*@8) */
  w4 *= w8;
  /* #42: @1 = (@1-@4) */
  w1 -= w4;
  /* #43: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #44: @1 = @0[9] */
  for (rr=(&w1), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #45: @4 = @0[10] */
  for (rr=(&w4), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #46: @8 = (@4*@5) */
  w8  = (w4*w5);
  /* #47: @7 = tan(@7) */
  w7 = tan( w7 );
  /* #48: @10 = (@8*@7) */
  w10  = (w8*w7);
  /* #49: @10 = (@1+@10) */
  w10  = (w1+w10);
  /* #50: @9 = @0[11] */
  for (rr=(&w9), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #51: @11 = (@9*@6) */
  w11  = (w9*w6);
  /* #52: @7 = (@11*@7) */
  w7  = (w11*w7);
  /* #53: @10 = (@10+@7) */
  w10 += w7;
  /* #54: output[0][6] = @10 */
  if (res[0]) res[0][6] = w10;
  /* #55: @6 = (@4*@6) */
  w6  = (w4*w6);
  /* #56: @5 = (@9*@5) */
  w5  = (w9*w5);
  /* #57: @6 = (@6-@5) */
  w6 -= w5;
  /* #58: output[0][7] = @6 */
  if (res[0]) res[0][7] = w6;
  /* #59: @8 = (@8/@3) */
  w8 /= w3;
  /* #60: @11 = (@11/@3) */
  w11 /= w3;
  /* #61: @8 = (@8+@11) */
  w8 += w11;
  /* #62: output[0][8] = @8 */
  if (res[0]) res[0][8] = w8;
  /* #63: @8 = 8.68614 */
  w8 = 8.6861373790280574e+00;
  /* #64: @11 = @2[3] */
  for (rr=(&w11), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #65: @3 = @0[13] */
  for (rr=(&w3), ss=w0+13; ss!=w0+14; ss+=1) *rr++ = *ss;
  /* #66: @11 = (@11+@3) */
  w11 += w3;
  /* #67: @3 = -0.113864 */
  w3 = -1.1386352300000001e-01;
  /* #68: @3 = (@3*@4) */
  w3 *= w4;
  /* #69: @3 = (@3*@9) */
  w3 *= w9;
  /* #70: @11 = (@11+@3) */
  w11 += w3;
  /* #71: @8 = (@8*@11) */
  w8 *= w11;
  /* #72: output[0][9] = @8 */
  if (res[0]) res[0][9] = w8;
  /* #73: @8 = 8.58191 */
  w8 = 8.5819061716340563e+00;
  /* #74: @11 = @2[4] */
  for (rr=(&w11), ss=w2+4; ss!=w2+5; ss+=1) *rr++ = *ss;
  /* #75: @3 = @0[14] */
  for (rr=(&w3), ss=w0+14; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #76: @11 = (@11+@3) */
  w11 += w3;
  /* #77: @3 = 0.115262 */
  w3 = 1.1526178100000001e-01;
  /* #78: @3 = (@3*@1) */
  w3 *= w1;
  /* #79: @3 = (@3*@9) */
  w3 *= w9;
  /* #80: @11 = (@11+@3) */
  w11 += w3;
  /* #81: @8 = (@8*@11) */
  w8 *= w11;
  /* #82: output[0][10] = @8 */
  if (res[0]) res[0][10] = w8;
  /* #83: @8 = 4.34051 */
  w8 = 4.3405085180048983e+00;
  /* #84: @11 = @2[5] */
  for (rr=(&w11), ss=w2+5; ss!=w2+6; ss+=1) *rr++ = *ss;
  /* #85: @3 = @0[15] */
  for (rr=(&w3), ss=w0+15; ss!=w0+16; ss+=1) *rr++ = *ss;
  /* #86: @11 = (@11+@3) */
  w11 += w3;
  /* #87: @3 = -0.00139826 */
  w3 = -1.3982579999999994e-03;
  /* #88: @3 = (@3*@1) */
  w3 *= w1;
  /* #89: @3 = (@3*@4) */
  w3 *= w4;
  /* #90: @11 = (@11+@3) */
  w11 += w3;
  /* #91: @8 = (@8*@11) */
  w8 *= w11;
  /* #92: output[0][11] = @8 */
  if (res[0]) res[0][11] = w8;
  /* #93: @13 = zeros(4x1) */
  casadi_clear(w13, 4);
  /* #94: output[0][12] = @13 */
  if (res[0]) casadi_copy(w13, 4, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hexarotor_model_adaptive_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hexarotor_model_adaptive_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hexarotor_model_adaptive_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void hexarotor_model_adaptive_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hexarotor_model_adaptive_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int hexarotor_model_adaptive_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hexarotor_model_adaptive_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hexarotor_model_adaptive_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hexarotor_model_adaptive_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hexarotor_model_adaptive_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hexarotor_model_adaptive_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 37;
  return 0;
}

CASADI_SYMBOL_EXPORT int hexarotor_model_adaptive_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 37*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
