/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tube_rates_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

/* tube_rates_model_expl_vde_adj:(i0[12],i1[12],i2[6],i3[0])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+12, w2, w3, *w4=w+26, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+65;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 12, w1);
  /* #2: @2 = @1[6] */
  for (rr=(&w2), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #3: @3 = cos(@2) */
  w3 = cos( w2 );
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 12, w4);
  /* #5: {@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16} = vertsplit(@4) */
  w5 = w4[0];
  w6 = w4[1];
  w7 = w4[2];
  w8 = w4[3];
  w9 = w4[4];
  w10 = w4[5];
  w11 = w4[6];
  w12 = w4[7];
  w13 = w4[8];
  w14 = w4[9];
  w15 = w4[10];
  w16 = w4[11];
  /* #6: @17 = @1[7] */
  for (rr=(&w17), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #7: @18 = cos(@17) */
  w18 = cos( w17 );
  /* #8: @19 = (@13/@18) */
  w19  = (w13/w18);
  /* #9: @20 = (@3*@19) */
  w20  = (w3*w19);
  /* #10: @21 = 0.1 */
  w21 = 1.0000000000000001e-01;
  /* #11: @16 = (@21*@16) */
  w16  = (w21*w16);
  /* #12: @20 = (@20-@16) */
  w20 -= w16;
  /* #13: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #14: @22 = (@2*@12) */
  w22  = (w2*w12);
  /* #15: @20 = (@20-@22) */
  w20 -= w22;
  /* #16: @22 = tan(@17) */
  w22 = tan( w17 );
  /* #17: @22 = (@22*@11) */
  w22 *= w11;
  /* #18: @23 = (@3*@22) */
  w23  = (w3*w22);
  /* #19: @20 = (@20+@23) */
  w20 += w23;
  /* #20: (@0[11] += @20) */
  for (rr=w0+11, ss=(&w20); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #21: @20 = (@2*@19) */
  w20  = (w2*w19);
  /* #22: @15 = (@21*@15) */
  w15  = (w21*w15);
  /* #23: @20 = (@20-@15) */
  w20 -= w15;
  /* #24: @23 = (@3*@12) */
  w23  = (w3*w12);
  /* #25: @20 = (@20+@23) */
  w20 += w23;
  /* #26: @23 = (@2*@22) */
  w23  = (w2*w22);
  /* #27: @20 = (@20+@23) */
  w20 += w23;
  /* #28: (@0[10] += @20) */
  for (rr=w0+10, ss=(&w20); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #29: @21 = (@21*@14) */
  w21 *= w14;
  /* #30: @14 = (@11-@21) */
  w14  = (w11-w21);
  /* #31: (@0[9] += @14) */
  for (rr=w0+9, ss=(&w14); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #32: @14 = @1[8] */
  for (rr=(&w14), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #33: @20 = cos(@14) */
  w20 = cos( w14 );
  /* #34: @17 = sin(@17) */
  w17 = sin( w17 );
  /* #35: @23 = (@3*@17) */
  w23  = (w3*w17);
  /* #36: @24 = 9.81 */
  w24 = 9.8100000000000005e+00;
  /* #37: @25 = (@24*@9) */
  w25  = (w24*w9);
  /* #38: @26 = (@23*@25) */
  w26  = (w23*w25);
  /* #39: @26 = (@20*@26) */
  w26  = (w20*w26);
  /* #40: @26 = (-@26) */
  w26 = (- w26 );
  /* #41: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #42: @27 = (@2*@25) */
  w27  = (w2*w25);
  /* #43: @27 = (@14*@27) */
  w27  = (w14*w27);
  /* #44: @26 = (@26-@27) */
  w26 -= w27;
  /* #45: @27 = (@24*@8) */
  w27  = (w24*w8);
  /* #46: @28 = (@2*@27) */
  w28  = (w2*w27);
  /* #47: @28 = (@20*@28) */
  w28  = (w20*w28);
  /* #48: @26 = (@26-@28) */
  w26 -= w28;
  /* #49: @23 = (@23*@27) */
  w23 *= w27;
  /* #50: @23 = (@14*@23) */
  w23  = (w14*w23);
  /* #51: @26 = (@26+@23) */
  w26 += w23;
  /* #52: (@0[8] += @26) */
  for (rr=w0+8, ss=(&w26); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #53: @26 = @1[11] */
  for (rr=(&w26), ss=w1+11; ss!=w1+12; ss+=1) *rr++ = *ss;
  /* #54: @23 = (@26*@3) */
  w23  = (w26*w3);
  /* #55: @28 = (@23/@18) */
  w28  = (w23/w18);
  /* #56: @28 = (@28/@18) */
  w28 /= w18;
  /* #57: @28 = (@28*@13) */
  w28 *= w13;
  /* #58: @28 = (@17*@28) */
  w28  = (w17*w28);
  /* #59: @29 = @1[10] */
  for (rr=(&w29), ss=w1+10; ss!=w1+11; ss+=1) *rr++ = *ss;
  /* #60: @30 = (@29*@2) */
  w30  = (w29*w2);
  /* #61: @31 = (@30/@18) */
  w31  = (w30/w18);
  /* #62: @31 = (@31/@18) */
  w31 /= w18;
  /* #63: @31 = (@31*@13) */
  w31 *= w13;
  /* #64: @31 = (@17*@31) */
  w31  = (w17*w31);
  /* #65: @28 = (@28+@31) */
  w28 += w31;
  /* #66: @23 = (@23*@11) */
  w23 *= w11;
  /* #67: @31 = sq(@18) */
  w31 = casadi_sq( w18 );
  /* #68: @23 = (@23/@31) */
  w23 /= w31;
  /* #69: @28 = (@28+@23) */
  w28 += w23;
  /* #70: @30 = (@30*@11) */
  w30 *= w11;
  /* #71: @30 = (@30/@31) */
  w30 /= w31;
  /* #72: @28 = (@28+@30) */
  w28 += w30;
  /* #73: @24 = (@24*@10) */
  w24 *= w10;
  /* #74: @30 = (@3*@24) */
  w30  = (w3*w24);
  /* #75: @30 = (@17*@30) */
  w30  = (w17*w30);
  /* #76: @28 = (@28+@30) */
  w28 += w30;
  /* #77: @30 = (@14*@25) */
  w30  = (w14*w25);
  /* #78: @31 = (@3*@30) */
  w31  = (w3*w30);
  /* #79: @31 = (@18*@31) */
  w31  = (w18*w31);
  /* #80: @28 = (@28-@31) */
  w28 -= w31;
  /* #81: @31 = (@20*@27) */
  w31  = (w20*w27);
  /* #82: @11 = (@3*@31) */
  w11  = (w3*w31);
  /* #83: @11 = (@18*@11) */
  w11  = (w18*w11);
  /* #84: @28 = (@28-@11) */
  w28 -= w11;
  /* #85: (@0[7] += @28) */
  for (rr=w0+7, ss=(&w28); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #86: @28 = (@29*@19) */
  w28  = (w29*w19);
  /* #87: @28 = (@3*@28) */
  w28  = (w3*w28);
  /* #88: @19 = (@26*@19) */
  w19  = (w26*w19);
  /* #89: @19 = (@2*@19) */
  w19  = (w2*w19);
  /* #90: @28 = (@28-@19) */
  w28 -= w19;
  /* #91: @19 = (@26*@12) */
  w19  = (w26*w12);
  /* #92: @19 = (@3*@19) */
  w19  = (w3*w19);
  /* #93: @28 = (@28-@19) */
  w28 -= w19;
  /* #94: @12 = (@29*@12) */
  w12  = (w29*w12);
  /* #95: @12 = (@2*@12) */
  w12  = (w2*w12);
  /* #96: @28 = (@28-@12) */
  w28 -= w12;
  /* #97: @26 = (@26*@22) */
  w26 *= w22;
  /* #98: @26 = (@2*@26) */
  w26  = (w2*w26);
  /* #99: @28 = (@28-@26) */
  w28 -= w26;
  /* #100: @29 = (@29*@22) */
  w29 *= w22;
  /* #101: @29 = (@3*@29) */
  w29  = (w3*w29);
  /* #102: @28 = (@28+@29) */
  w28 += w29;
  /* #103: @18 = (@18*@24) */
  w18 *= w24;
  /* #104: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #105: @28 = (@28+@18) */
  w28 += w18;
  /* #106: @20 = (@20*@25) */
  w20 *= w25;
  /* #107: @20 = (@3*@20) */
  w20  = (w3*w20);
  /* #108: @28 = (@28+@20) */
  w28 += w20;
  /* #109: @30 = (@17*@30) */
  w30  = (w17*w30);
  /* #110: @30 = (@2*@30) */
  w30  = (w2*w30);
  /* #111: @28 = (@28+@30) */
  w28 += w30;
  /* #112: @14 = (@14*@27) */
  w14 *= w27;
  /* #113: @3 = (@3*@14) */
  w3 *= w14;
  /* #114: @28 = (@28-@3) */
  w28 -= w3;
  /* #115: @17 = (@17*@31) */
  w17 *= w31;
  /* #116: @2 = (@2*@17) */
  w2 *= w17;
  /* #117: @28 = (@28+@2) */
  w28 += w2;
  /* #118: (@0[6] += @28) */
  for (rr=w0+6, ss=(&w28); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #119: (@0[5] += @7) */
  for (rr=w0+5, ss=(&w7); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #120: (@0[4] += @6) */
  for (rr=w0+4, ss=(&w6); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #121: (@0[3] += @5) */
  for (rr=w0+3, ss=(&w5); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #122: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  /* #123: @32 = zeros(6x1) */
  casadi_clear(w32, 6);
  /* #124: (@32[5] += @16) */
  for (rr=w32+5, ss=(&w16); rr!=w32+6; rr+=1) *rr += *ss++;
  /* #125: (@32[4] += @15) */
  for (rr=w32+4, ss=(&w15); rr!=w32+5; rr+=1) *rr += *ss++;
  /* #126: (@32[3] += @21) */
  for (rr=w32+3, ss=(&w21); rr!=w32+4; rr+=1) *rr += *ss++;
  /* #127: @21 = 0.142857 */
  w21 = 1.4285714285714285e-01;
  /* #128: @10 = (@21*@10) */
  w10  = (w21*w10);
  /* #129: (@32[2] += @10) */
  for (rr=w32+2, ss=(&w10); rr!=w32+3; rr+=1) *rr += *ss++;
  /* #130: @9 = (@21*@9) */
  w9  = (w21*w9);
  /* #131: (@32[1] += @9) */
  for (rr=w32+1, ss=(&w9); rr!=w32+2; rr+=1) *rr += *ss++;
  /* #132: @21 = (@21*@8) */
  w21 *= w8;
  /* #133: (@32[0] += @21) */
  for (rr=w32+0, ss=(&w21); rr!=w32+1; rr+=1) *rr += *ss++;
  /* #134: output[0][1] = @32 */
  if (res[0]) casadi_copy(w32, 6, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int tube_rates_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tube_rates_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tube_rates_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tube_rates_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tube_rates_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tube_rates_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tube_rates_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void tube_rates_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tube_rates_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tube_rates_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tube_rates_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tube_rates_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tube_rates_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tube_rates_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tube_rates_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tube_rates_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 71;
  return 0;
}

CASADI_SYMBOL_EXPORT int tube_rates_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 71*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
