/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hex_with_nn_residual_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};

/* hex_with_nn_residual_expl_vde_adj:(i0[12],i1[12],i2[6],i3[0])->(o0[18]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, *w3=w+14, w4, w5, *w6=w+28, w7, *w8=w+35, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34;
  /* #0: @0 = zeros(12x1) */
  casadi_clear(w0, 12);
  /* #1: @1 = 0.1 */
  w1 = 1.0000000000000001e-01;
  /* #2: @2 = 1.1 */
  w2 = 1.1000000000000001e+00;
  /* #3: @3 = input[0][0] */
  casadi_copy(arg[0], 12, w3);
  /* #4: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #5: @5 = @3[3] */
  for (rr=(&w5), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #6: @5 = (@1*@5) */
  w5  = (w1*w5);
  /* #7: @4 = (@4+@5) */
  w4 += w5;
  /* #8: @5 = 0.01 */
  w5 = 1.0000000000000000e-02;
  /* #9: @6 = input[2][0] */
  casadi_copy(arg[2], 6, w6);
  /* #10: @7 = @6[0] */
  for (rr=(&w7), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #11: @7 = (@5*@7) */
  w7  = (w5*w7);
  /* #12: @4 = (@4+@7) */
  w4 += w7;
  /* #13: @2 = (@2+@4) */
  w2 += w4;
  /* #14: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #15: @8 = input[1][0] */
  casadi_copy(arg[1], 12, w8);
  /* #16: {@7, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19} = vertsplit(@8) */
  w7 = w8[0];
  w9 = w8[1];
  w10 = w8[2];
  w11 = w8[3];
  w12 = w8[4];
  w13 = w8[5];
  w14 = w8[6];
  w15 = w8[7];
  w16 = w8[8];
  w17 = w8[9];
  w18 = w8[10];
  w19 = w8[11];
  /* #17: @20 = (@5*@19) */
  w20  = (w5*w19);
  /* #18: @2 = (@2*@20) */
  w2 *= w20;
  /* #19: @20 = 1 */
  w20 = 1.;
  /* #20: @20 = (@20+@4) */
  w20 += w4;
  /* #21: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #22: @21 = (@5*@18) */
  w21  = (w5*w18);
  /* #23: @20 = (@20*@21) */
  w20 *= w21;
  /* #24: @2 = (@2+@20) */
  w2 += w20;
  /* #25: @20 = 0.9 */
  w20 = 9.0000000000000002e-01;
  /* #26: @20 = (@20+@4) */
  w20 += w4;
  /* #27: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #28: @21 = (@5*@17) */
  w21  = (w5*w17);
  /* #29: @20 = (@20*@21) */
  w20 *= w21;
  /* #30: @2 = (@2+@20) */
  w2 += w20;
  /* #31: @20 = 0.8 */
  w20 = 8.0000000000000004e-01;
  /* #32: @20 = (@20+@4) */
  w20 += w4;
  /* #33: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #34: @21 = (@5*@16) */
  w21  = (w5*w16);
  /* #35: @20 = (@20*@21) */
  w20 *= w21;
  /* #36: @2 = (@2+@20) */
  w2 += w20;
  /* #37: @20 = 0.7 */
  w20 = 7.0000000000000007e-01;
  /* #38: @20 = (@20+@4) */
  w20 += w4;
  /* #39: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #40: @21 = (@5*@15) */
  w21  = (w5*w15);
  /* #41: @20 = (@20*@21) */
  w20 *= w21;
  /* #42: @2 = (@2+@20) */
  w2 += w20;
  /* #43: @20 = 0.6 */
  w20 = 6.0000000000000009e-01;
  /* #44: @20 = (@20+@4) */
  w20 += w4;
  /* #45: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #46: @21 = (@5*@14) */
  w21  = (w5*w14);
  /* #47: @20 = (@20*@21) */
  w20 *= w21;
  /* #48: @2 = (@2+@20) */
  w2 += w20;
  /* #49: @20 = 0.5 */
  w20 = 5.0000000000000000e-01;
  /* #50: @20 = (@20+@4) */
  w20 += w4;
  /* #51: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #52: @21 = (@5*@13) */
  w21  = (w5*w13);
  /* #53: @20 = (@20*@21) */
  w20 *= w21;
  /* #54: @2 = (@2+@20) */
  w2 += w20;
  /* #55: @20 = 0.4 */
  w20 = 4.0000000000000002e-01;
  /* #56: @20 = (@20+@4) */
  w20 += w4;
  /* #57: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #58: @21 = (@5*@12) */
  w21  = (w5*w12);
  /* #59: @20 = (@20*@21) */
  w20 *= w21;
  /* #60: @2 = (@2+@20) */
  w2 += w20;
  /* #61: @20 = 0.3 */
  w20 = 3.0000000000000004e-01;
  /* #62: @20 = (@20+@4) */
  w20 += w4;
  /* #63: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #64: @21 = (@5*@11) */
  w21  = (w5*w11);
  /* #65: @20 = (@20*@21) */
  w20 *= w21;
  /* #66: @2 = (@2+@20) */
  w2 += w20;
  /* #67: @20 = 0.2 */
  w20 = 2.0000000000000001e-01;
  /* #68: @20 = (@20+@4) */
  w20 += w4;
  /* #69: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #70: @21 = (@5*@10) */
  w21  = (w5*w10);
  /* #71: @20 = (@20*@21) */
  w20 *= w21;
  /* #72: @2 = (@2+@20) */
  w2 += w20;
  /* #73: @20 = (@1+@4) */
  w20  = (w1+w4);
  /* #74: @20 = cos(@20) */
  w20 = cos( w20 );
  /* #75: @21 = (@5*@9) */
  w21  = (w5*w9);
  /* #76: @20 = (@20*@21) */
  w20 *= w21;
  /* #77: @2 = (@2+@20) */
  w2 += w20;
  /* #78: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #79: @20 = (@5*@7) */
  w20  = (w5*w7);
  /* #80: @4 = (@4*@20) */
  w4 *= w20;
  /* #81: @2 = (@2+@4) */
  w2 += w4;
  /* #82: @1 = (@1*@2) */
  w1 *= w2;
  /* #83: (@0[3] += @1) */
  for (rr=w0+3, ss=(&w1); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #84: (@0[0] += @2) */
  for (rr=w0+0, ss=(&w2); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #85: @1 = 0.115262 */
  w1 = 1.1526178100000001e-01;
  /* #86: @4 = @3[9] */
  for (rr=(&w4), ss=w3+9; ss!=w3+10; ss+=1) *rr++ = *ss;
  /* #87: @20 = (@1*@4) */
  w20  = (w1*w4);
  /* #88: @21 = 8.58191 */
  w21 = 8.5819061716340563e+00;
  /* #89: @21 = (@21*@18) */
  w21 *= w18;
  /* #90: @20 = (@20*@21) */
  w20 *= w21;
  /* #91: @18 = -0.113864 */
  w18 = -1.1386352300000001e-01;
  /* #92: @22 = @3[10] */
  for (rr=(&w22), ss=w3+10; ss!=w3+11; ss+=1) *rr++ = *ss;
  /* #93: @23 = (@18*@22) */
  w23  = (w18*w22);
  /* #94: @24 = 8.68614 */
  w24 = 8.6861373790280574e+00;
  /* #95: @24 = (@24*@17) */
  w24 *= w17;
  /* #96: @23 = (@23*@24) */
  w23 *= w24;
  /* #97: @20 = (@20+@23) */
  w20 += w23;
  /* #98: @23 = @3[6] */
  for (rr=(&w23), ss=w3+6; ss!=w3+7; ss+=1) *rr++ = *ss;
  /* #99: @17 = cos(@23) */
  w17 = cos( w23 );
  /* #100: @25 = @3[7] */
  for (rr=(&w25), ss=w3+7; ss!=w3+8; ss+=1) *rr++ = *ss;
  /* #101: @26 = cos(@25) */
  w26 = cos( w25 );
  /* #102: @27 = (@16/@26) */
  w27  = (w16/w26);
  /* #103: @28 = (@17*@27) */
  w28  = (w17*w27);
  /* #104: @20 = (@20+@28) */
  w20 += w28;
  /* #105: @23 = sin(@23) */
  w23 = sin( w23 );
  /* #106: @28 = (@23*@15) */
  w28  = (w23*w15);
  /* #107: @20 = (@20-@28) */
  w20 -= w28;
  /* #108: @28 = tan(@25) */
  w28 = tan( w25 );
  /* #109: @28 = (@28*@14) */
  w28 *= w14;
  /* #110: @29 = (@17*@28) */
  w29  = (w17*w28);
  /* #111: @20 = (@20+@29) */
  w20 += w29;
  /* #112: (@0[11] += @20) */
  for (rr=w0+11, ss=(&w20); rr!=w0+12; rr+=1) *rr += *ss++;
  /* #113: @20 = -0.00139826 */
  w20 = -1.3982579999999994e-03;
  /* #114: @4 = (@20*@4) */
  w4  = (w20*w4);
  /* #115: @29 = 4.34051 */
  w29 = 4.3405085180048983e+00;
  /* #116: @29 = (@29*@19) */
  w29 *= w19;
  /* #117: @4 = (@4*@29) */
  w4 *= w29;
  /* #118: @19 = @3[11] */
  for (rr=(&w19), ss=w3+11; ss!=w3+12; ss+=1) *rr++ = *ss;
  /* #119: @30 = (@19*@24) */
  w30  = (w19*w24);
  /* #120: @18 = (@18*@30) */
  w18 *= w30;
  /* #121: @4 = (@4+@18) */
  w4 += w18;
  /* #122: @18 = (@23*@27) */
  w18  = (w23*w27);
  /* #123: @4 = (@4+@18) */
  w4 += w18;
  /* #124: @18 = (@17*@15) */
  w18  = (w17*w15);
  /* #125: @4 = (@4+@18) */
  w4 += w18;
  /* #126: @18 = (@23*@28) */
  w18  = (w23*w28);
  /* #127: @4 = (@4+@18) */
  w4 += w18;
  /* #128: (@0[10] += @4) */
  for (rr=w0+10, ss=(&w4); rr!=w0+11; rr+=1) *rr += *ss++;
  /* #129: @4 = (@22*@29) */
  w4  = (w22*w29);
  /* #130: @20 = (@20*@4) */
  w20 *= w4;
  /* #131: @4 = (@19*@21) */
  w4  = (w19*w21);
  /* #132: @1 = (@1*@4) */
  w1 *= w4;
  /* #133: @20 = (@20+@1) */
  w20 += w1;
  /* #134: @20 = (@20+@14) */
  w20 += w14;
  /* #135: (@0[9] += @20) */
  for (rr=w0+9, ss=(&w20); rr!=w0+10; rr+=1) *rr += *ss++;
  /* #136: @20 = @3[8] */
  for (rr=(&w20), ss=w3+8; ss!=w3+9; ss+=1) *rr++ = *ss;
  /* #137: @1 = cos(@20) */
  w1 = cos( w20 );
  /* #138: @25 = sin(@25) */
  w25 = sin( w25 );
  /* #139: @4 = (@17*@25) */
  w4  = (w17*w25);
  /* #140: @18 = 9.81 */
  w18 = 9.8100000000000005e+00;
  /* #141: @30 = (@18*@12) */
  w30  = (w18*w12);
  /* #142: @31 = (@4*@30) */
  w31  = (w4*w30);
  /* #143: @31 = (@1*@31) */
  w31  = (w1*w31);
  /* #144: @31 = (-@31) */
  w31 = (- w31 );
  /* #145: @20 = sin(@20) */
  w20 = sin( w20 );
  /* #146: @32 = (@23*@30) */
  w32  = (w23*w30);
  /* #147: @32 = (@20*@32) */
  w32  = (w20*w32);
  /* #148: @31 = (@31-@32) */
  w31 -= w32;
  /* #149: @32 = (@18*@11) */
  w32  = (w18*w11);
  /* #150: @33 = (@23*@32) */
  w33  = (w23*w32);
  /* #151: @33 = (@1*@33) */
  w33  = (w1*w33);
  /* #152: @31 = (@31-@33) */
  w31 -= w33;
  /* #153: @4 = (@4*@32) */
  w4 *= w32;
  /* #154: @4 = (@20*@4) */
  w4  = (w20*w4);
  /* #155: @31 = (@31+@4) */
  w31 += w4;
  /* #156: (@0[8] += @31) */
  for (rr=w0+8, ss=(&w31); rr!=w0+9; rr+=1) *rr += *ss++;
  /* #157: @31 = (@19*@17) */
  w31  = (w19*w17);
  /* #158: @4 = (@31/@26) */
  w4  = (w31/w26);
  /* #159: @4 = (@4/@26) */
  w4 /= w26;
  /* #160: @4 = (@4*@16) */
  w4 *= w16;
  /* #161: @4 = (@25*@4) */
  w4  = (w25*w4);
  /* #162: @33 = (@22*@23) */
  w33  = (w22*w23);
  /* #163: @34 = (@33/@26) */
  w34  = (w33/w26);
  /* #164: @34 = (@34/@26) */
  w34 /= w26;
  /* #165: @34 = (@34*@16) */
  w34 *= w16;
  /* #166: @34 = (@25*@34) */
  w34  = (w25*w34);
  /* #167: @4 = (@4+@34) */
  w4 += w34;
  /* #168: @31 = (@31*@14) */
  w31 *= w14;
  /* #169: @34 = sq(@26) */
  w34 = casadi_sq( w26 );
  /* #170: @31 = (@31/@34) */
  w31 /= w34;
  /* #171: @4 = (@4+@31) */
  w4 += w31;
  /* #172: @33 = (@33*@14) */
  w33 *= w14;
  /* #173: @33 = (@33/@34) */
  w33 /= w34;
  /* #174: @4 = (@4+@33) */
  w4 += w33;
  /* #175: @18 = (@18*@13) */
  w18 *= w13;
  /* #176: @33 = (@17*@18) */
  w33  = (w17*w18);
  /* #177: @33 = (@25*@33) */
  w33  = (w25*w33);
  /* #178: @4 = (@4+@33) */
  w4 += w33;
  /* #179: @33 = (@20*@30) */
  w33  = (w20*w30);
  /* #180: @34 = (@17*@33) */
  w34  = (w17*w33);
  /* #181: @34 = (@26*@34) */
  w34  = (w26*w34);
  /* #182: @4 = (@4-@34) */
  w4 -= w34;
  /* #183: @34 = (@1*@32) */
  w34  = (w1*w32);
  /* #184: @14 = (@17*@34) */
  w14  = (w17*w34);
  /* #185: @14 = (@26*@14) */
  w14  = (w26*w14);
  /* #186: @4 = (@4-@14) */
  w4 -= w14;
  /* #187: (@0[7] += @4) */
  for (rr=w0+7, ss=(&w4); rr!=w0+8; rr+=1) *rr += *ss++;
  /* #188: @4 = (@22*@27) */
  w4  = (w22*w27);
  /* #189: @4 = (@17*@4) */
  w4  = (w17*w4);
  /* #190: @27 = (@19*@27) */
  w27  = (w19*w27);
  /* #191: @27 = (@23*@27) */
  w27  = (w23*w27);
  /* #192: @4 = (@4-@27) */
  w4 -= w27;
  /* #193: @27 = (@19*@15) */
  w27  = (w19*w15);
  /* #194: @27 = (@17*@27) */
  w27  = (w17*w27);
  /* #195: @4 = (@4-@27) */
  w4 -= w27;
  /* #196: @15 = (@22*@15) */
  w15  = (w22*w15);
  /* #197: @15 = (@23*@15) */
  w15  = (w23*w15);
  /* #198: @4 = (@4-@15) */
  w4 -= w15;
  /* #199: @19 = (@19*@28) */
  w19 *= w28;
  /* #200: @19 = (@23*@19) */
  w19  = (w23*w19);
  /* #201: @4 = (@4-@19) */
  w4 -= w19;
  /* #202: @22 = (@22*@28) */
  w22 *= w28;
  /* #203: @22 = (@17*@22) */
  w22  = (w17*w22);
  /* #204: @4 = (@4+@22) */
  w4 += w22;
  /* #205: @26 = (@26*@18) */
  w26 *= w18;
  /* #206: @26 = (@23*@26) */
  w26  = (w23*w26);
  /* #207: @4 = (@4+@26) */
  w4 += w26;
  /* #208: @1 = (@1*@30) */
  w1 *= w30;
  /* #209: @1 = (@17*@1) */
  w1  = (w17*w1);
  /* #210: @4 = (@4+@1) */
  w4 += w1;
  /* #211: @33 = (@25*@33) */
  w33  = (w25*w33);
  /* #212: @33 = (@23*@33) */
  w33  = (w23*w33);
  /* #213: @4 = (@4+@33) */
  w4 += w33;
  /* #214: @20 = (@20*@32) */
  w20 *= w32;
  /* #215: @17 = (@17*@20) */
  w17 *= w20;
  /* #216: @4 = (@4-@17) */
  w4 -= w17;
  /* #217: @25 = (@25*@34) */
  w25 *= w34;
  /* #218: @23 = (@23*@25) */
  w23 *= w25;
  /* #219: @4 = (@4+@23) */
  w4 += w23;
  /* #220: (@0[6] += @4) */
  for (rr=w0+6, ss=(&w4); rr!=w0+7; rr+=1) *rr += *ss++;
  /* #221: (@0[5] += @10) */
  for (rr=w0+5, ss=(&w10); rr!=w0+6; rr+=1) *rr += *ss++;
  /* #222: (@0[4] += @9) */
  for (rr=w0+4, ss=(&w9); rr!=w0+5; rr+=1) *rr += *ss++;
  /* #223: (@0[3] += @7) */
  for (rr=w0+3, ss=(&w7); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #224: output[0][0] = @0 */
  casadi_copy(w0, 12, res[0]);
  /* #225: @6 = zeros(6x1) */
  casadi_clear(w6, 6);
  /* #226: @5 = (@5*@2) */
  w5 *= w2;
  /* #227: (@6[0] += @5) */
  for (rr=w6+0, ss=(&w5); rr!=w6+1; rr+=1) *rr += *ss++;
  /* #228: (@6[5] += @29) */
  for (rr=w6+5, ss=(&w29); rr!=w6+6; rr+=1) *rr += *ss++;
  /* #229: (@6[4] += @21) */
  for (rr=w6+4, ss=(&w21); rr!=w6+5; rr+=1) *rr += *ss++;
  /* #230: (@6[3] += @24) */
  for (rr=w6+3, ss=(&w24); rr!=w6+4; rr+=1) *rr += *ss++;
  /* #231: @24 = 0.142857 */
  w24 = 1.4285714285714285e-01;
  /* #232: @13 = (@24*@13) */
  w13  = (w24*w13);
  /* #233: (@6[2] += @13) */
  for (rr=w6+2, ss=(&w13); rr!=w6+3; rr+=1) *rr += *ss++;
  /* #234: @12 = (@24*@12) */
  w12  = (w24*w12);
  /* #235: (@6[1] += @12) */
  for (rr=w6+1, ss=(&w12); rr!=w6+2; rr+=1) *rr += *ss++;
  /* #236: @24 = (@24*@11) */
  w24 *= w11;
  /* #237: (@6[0] += @24) */
  for (rr=w6+0, ss=(&w24); rr!=w6+1; rr+=1) *rr += *ss++;
  /* #238: output[0][1] = @6 */
  if (res[0]) casadi_copy(w6, 6, res[0]+12);
  return 0;
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hex_with_nn_residual_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hex_with_nn_residual_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hex_with_nn_residual_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void hex_with_nn_residual_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hex_with_nn_residual_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int hex_with_nn_residual_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hex_with_nn_residual_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hex_with_nn_residual_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hex_with_nn_residual_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hex_with_nn_residual_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hex_with_nn_residual_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 73;
  return 0;
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 13*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 73*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
