/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hex_with_nn_residual_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};

/* hex_with_nn_residual_expl_ode_fun:(i0[12],i1[6],i2[0])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, *w4=w+15, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+35;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 12, w0);
  /* #1: @1 = @0[3] */
  for (rr=(&w1), ss=w0+3; ss!=w0+4; ss+=1) *rr++ = *ss;
  /* #2: @2 = @0[4] */
  for (rr=(&w2), ss=w0+4; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #3: @3 = @0[5] */
  for (rr=(&w3), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 6, w4);
  /* #5: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #6: @6 = 7 */
  w6 = 7.;
  /* #7: @7 = (@5/@6) */
  w7  = (w5/w6);
  /* #8: @8 = 9.81 */
  w8 = 9.8100000000000005e+00;
  /* #9: @9 = @0[6] */
  for (rr=(&w9), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #10: @10 = cos(@9) */
  w10 = cos( w9 );
  /* #11: @11 = @0[7] */
  for (rr=(&w11), ss=w0+7; ss!=w0+8; ss+=1) *rr++ = *ss;
  /* #12: @12 = sin(@11) */
  w12 = sin( w11 );
  /* #13: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #14: @13 = @0[8] */
  for (rr=(&w13), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #15: @14 = cos(@13) */
  w14 = cos( w13 );
  /* #16: @15 = (@12*@14) */
  w15  = (w12*w14);
  /* #17: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #18: @13 = sin(@13) */
  w13 = sin( w13 );
  /* #19: @16 = (@9*@13) */
  w16  = (w9*w13);
  /* #20: @15 = (@15+@16) */
  w15 += w16;
  /* #21: @15 = (@8*@15) */
  w15  = (w8*w15);
  /* #22: @7 = (@7-@15) */
  w7 -= w15;
  /* #23: @15 = @4[1] */
  for (rr=(&w15), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #24: @15 = (@15/@6) */
  w15 /= w6;
  /* #25: @12 = (@12*@13) */
  w12 *= w13;
  /* #26: @14 = (@9*@14) */
  w14  = (w9*w14);
  /* #27: @12 = (@12-@14) */
  w12 -= w14;
  /* #28: @12 = (@8*@12) */
  w12  = (w8*w12);
  /* #29: @15 = (@15-@12) */
  w15 -= w12;
  /* #30: @12 = @4[2] */
  for (rr=(&w12), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #31: @12 = (@12/@6) */
  w12 /= w6;
  /* #32: @6 = cos(@11) */
  w6 = cos( w11 );
  /* #33: @14 = (@10*@6) */
  w14  = (w10*w6);
  /* #34: @8 = (@8*@14) */
  w8 *= w14;
  /* #35: @12 = (@12-@8) */
  w12 -= w8;
  /* #36: @8 = @0[9] */
  for (rr=(&w8), ss=w0+9; ss!=w0+10; ss+=1) *rr++ = *ss;
  /* #37: @14 = @0[10] */
  for (rr=(&w14), ss=w0+10; ss!=w0+11; ss+=1) *rr++ = *ss;
  /* #38: @13 = (@14*@9) */
  w13  = (w14*w9);
  /* #39: @11 = tan(@11) */
  w11 = tan( w11 );
  /* #40: @16 = (@13*@11) */
  w16  = (w13*w11);
  /* #41: @16 = (@8+@16) */
  w16  = (w8+w16);
  /* #42: @17 = @0[11] */
  for (rr=(&w17), ss=w0+11; ss!=w0+12; ss+=1) *rr++ = *ss;
  /* #43: @18 = (@17*@10) */
  w18  = (w17*w10);
  /* #44: @11 = (@18*@11) */
  w11  = (w18*w11);
  /* #45: @16 = (@16+@11) */
  w16 += w11;
  /* #46: @10 = (@14*@10) */
  w10  = (w14*w10);
  /* #47: @9 = (@17*@9) */
  w9  = (w17*w9);
  /* #48: @10 = (@10-@9) */
  w10 -= w9;
  /* #49: @13 = (@13/@6) */
  w13 /= w6;
  /* #50: @18 = (@18/@6) */
  w18 /= w6;
  /* #51: @13 = (@13+@18) */
  w13 += w18;
  /* #52: @18 = 8.68614 */
  w18 = 8.6861373790280574e+00;
  /* #53: @6 = @4[3] */
  for (rr=(&w6), ss=w4+3; ss!=w4+4; ss+=1) *rr++ = *ss;
  /* #54: @9 = -0.113864 */
  w9 = -1.1386352300000001e-01;
  /* #55: @9 = (@9*@14) */
  w9 *= w14;
  /* #56: @9 = (@9*@17) */
  w9 *= w17;
  /* #57: @6 = (@6+@9) */
  w6 += w9;
  /* #58: @18 = (@18*@6) */
  w18 *= w6;
  /* #59: @6 = 8.58191 */
  w6 = 8.5819061716340563e+00;
  /* #60: @9 = @4[4] */
  for (rr=(&w9), ss=w4+4; ss!=w4+5; ss+=1) *rr++ = *ss;
  /* #61: @11 = 0.115262 */
  w11 = 1.1526178100000001e-01;
  /* #62: @11 = (@11*@8) */
  w11 *= w8;
  /* #63: @11 = (@11*@17) */
  w11 *= w17;
  /* #64: @9 = (@9+@11) */
  w9 += w11;
  /* #65: @6 = (@6*@9) */
  w6 *= w9;
  /* #66: @9 = 4.34051 */
  w9 = 4.3405085180048983e+00;
  /* #67: @11 = @4[5] */
  for (rr=(&w11), ss=w4+5; ss!=w4+6; ss+=1) *rr++ = *ss;
  /* #68: @17 = -0.00139826 */
  w17 = -1.3982579999999994e-03;
  /* #69: @17 = (@17*@8) */
  w17 *= w8;
  /* #70: @17 = (@17*@14) */
  w17 *= w14;
  /* #71: @11 = (@11+@17) */
  w11 += w17;
  /* #72: @9 = (@9*@11) */
  w9 *= w11;
  /* #73: @19 = vertcat(@1, @2, @3, @7, @15, @12, @16, @10, @13, @18, @6, @9) */
  rr=w19;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w7;
  *rr++ = w15;
  *rr++ = w12;
  *rr++ = w16;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w18;
  *rr++ = w6;
  *rr++ = w9;
  /* #74: @2 = 0.01 */
  w2 = 1.0000000000000000e-02;
  /* #75: @3 = @0[0] */
  for (rr=(&w3), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #76: @7 = 0.1 */
  w7 = 1.0000000000000001e-01;
  /* #77: @1 = (@7*@1) */
  w1  = (w7*w1);
  /* #78: @3 = (@3+@1) */
  w3 += w1;
  /* #79: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #80: @3 = (@3+@5) */
  w3 += w5;
  /* #81: @5 = sin(@3) */
  w5 = sin( w3 );
  /* #82: @5 = (@2*@5) */
  w5  = (w2*w5);
  /* #83: @7 = (@7+@3) */
  w7 += w3;
  /* #84: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #85: @7 = (@2*@7) */
  w7  = (w2*w7);
  /* #86: @1 = 0.2 */
  w1 = 2.0000000000000001e-01;
  /* #87: @1 = (@1+@3) */
  w1 += w3;
  /* #88: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #89: @1 = (@2*@1) */
  w1  = (w2*w1);
  /* #90: @15 = 0.3 */
  w15 = 3.0000000000000004e-01;
  /* #91: @15 = (@15+@3) */
  w15 += w3;
  /* #92: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #93: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #94: @12 = 0.4 */
  w12 = 4.0000000000000002e-01;
  /* #95: @12 = (@12+@3) */
  w12 += w3;
  /* #96: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #97: @12 = (@2*@12) */
  w12  = (w2*w12);
  /* #98: @16 = 0.5 */
  w16 = 5.0000000000000000e-01;
  /* #99: @16 = (@16+@3) */
  w16 += w3;
  /* #100: @16 = sin(@16) */
  w16 = sin( w16 );
  /* #101: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #102: @10 = 0.6 */
  w10 = 6.0000000000000009e-01;
  /* #103: @10 = (@10+@3) */
  w10 += w3;
  /* #104: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #105: @10 = (@2*@10) */
  w10  = (w2*w10);
  /* #106: @13 = 0.7 */
  w13 = 7.0000000000000007e-01;
  /* #107: @13 = (@13+@3) */
  w13 += w3;
  /* #108: @13 = sin(@13) */
  w13 = sin( w13 );
  /* #109: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #110: @18 = 0.8 */
  w18 = 8.0000000000000004e-01;
  /* #111: @18 = (@18+@3) */
  w18 += w3;
  /* #112: @18 = sin(@18) */
  w18 = sin( w18 );
  /* #113: @18 = (@2*@18) */
  w18  = (w2*w18);
  /* #114: @6 = 0.9 */
  w6 = 9.0000000000000002e-01;
  /* #115: @6 = (@6+@3) */
  w6 += w3;
  /* #116: @6 = sin(@6) */
  w6 = sin( w6 );
  /* #117: @6 = (@2*@6) */
  w6  = (w2*w6);
  /* #118: @9 = 1 */
  w9 = 1.;
  /* #119: @9 = (@9+@3) */
  w9 += w3;
  /* #120: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #121: @9 = (@2*@9) */
  w9  = (w2*w9);
  /* #122: @11 = 1.1 */
  w11 = 1.1000000000000001e+00;
  /* #123: @11 = (@11+@3) */
  w11 += w3;
  /* #124: @11 = sin(@11) */
  w11 = sin( w11 );
  /* #125: @2 = (@2*@11) */
  w2 *= w11;
  /* #126: @0 = vertcat(@5, @7, @1, @15, @12, @16, @10, @13, @18, @6, @9, @2) */
  rr=w0;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w1;
  *rr++ = w15;
  *rr++ = w12;
  *rr++ = w16;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w18;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w2;
  /* #127: @19 = (@19+@0) */
  for (i=0, rr=w19, cs=w0; i<12; ++i) (*rr++) += (*cs++);
  /* #128: output[0][0] = @19 */
  casadi_copy(w19, 12, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hex_with_nn_residual_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hex_with_nn_residual_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hex_with_nn_residual_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void hex_with_nn_residual_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hex_with_nn_residual_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int hex_with_nn_residual_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hex_with_nn_residual_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hex_with_nn_residual_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hex_with_nn_residual_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hex_with_nn_residual_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hex_with_nn_residual_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 47;
  return 0;
}

CASADI_SYMBOL_EXPORT int hex_with_nn_residual_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 47*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
